# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiNameRelationship(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'ImdbapiName',
        'relation_type': 'str',
        'attributes': 'list[str]'
    }

    attribute_map = {
        'name': 'name',
        'relation_type': 'relationType',
        'attributes': 'attributes'
    }

    def __init__(self, name=None, relation_type=None, attributes=None, _configuration=None):  # noqa: E501
        """ImdbapiNameRelationship - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._name = None
        self._relation_type = None
        self._attributes = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if relation_type is not None:
            self.relation_type = relation_type
        if attributes is not None:
            self.attributes = attributes

    @property
    def name(self):
        """Gets the name of this ImdbapiNameRelationship.  # noqa: E501

        The related name in the relationship.  # noqa: E501

        :return: The name of this ImdbapiNameRelationship.  # noqa: E501
        :rtype: ImdbapiName
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ImdbapiNameRelationship.

        The related name in the relationship.  # noqa: E501

        :param name: The name of this ImdbapiNameRelationship.  # noqa: E501
        :type: ImdbapiName
        """

        self._name = name

    @property
    def relation_type(self):
        """Gets the relation_type of this ImdbapiNameRelationship.  # noqa: E501

        The type of relationship, such as \"spouse\", \"parent\", \"child\", etc.  # noqa: E501

        :return: The relation_type of this ImdbapiNameRelationship.  # noqa: E501
        :rtype: str
        """
        return self._relation_type

    @relation_type.setter
    def relation_type(self, relation_type):
        """Sets the relation_type of this ImdbapiNameRelationship.

        The type of relationship, such as \"spouse\", \"parent\", \"child\", etc.  # noqa: E501

        :param relation_type: The relation_type of this ImdbapiNameRelationship.  # noqa: E501
        :type: str
        """

        self._relation_type = relation_type

    @property
    def attributes(self):
        """Gets the attributes of this ImdbapiNameRelationship.  # noqa: E501

        Additional attributes associated with the relationship.  # noqa: E501

        :return: The attributes of this ImdbapiNameRelationship.  # noqa: E501
        :rtype: list[str]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this ImdbapiNameRelationship.

        Additional attributes associated with the relationship.  # noqa: E501

        :param attributes: The attributes of this ImdbapiNameRelationship.  # noqa: E501
        :type: list[str]
        """

        self._attributes = attributes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiNameRelationship, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiNameRelationship):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiNameRelationship):
            return True

        return self.to_dict() != other.to_dict()
