# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiCompanyCredit(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'company': 'ImdbapiCompany',
        'category': 'str',
        'countries': 'list[ImdbapiCountry]',
        'years_involved': 'ImdbapiYearsInvolved',
        'attributes': 'list[str]'
    }

    attribute_map = {
        'company': 'company',
        'category': 'category',
        'countries': 'countries',
        'years_involved': 'yearsInvolved',
        'attributes': 'attributes'
    }

    def __init__(self, company=None, category=None, countries=None, years_involved=None, attributes=None, _configuration=None):  # noqa: E501
        """ImdbapiCompanyCredit - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._company = None
        self._category = None
        self._countries = None
        self._years_involved = None
        self._attributes = None
        self.discriminator = None

        if company is not None:
            self.company = company
        if category is not None:
            self.category = category
        if countries is not None:
            self.countries = countries
        if years_involved is not None:
            self.years_involved = years_involved
        if attributes is not None:
            self.attributes = attributes

    @property
    def company(self):
        """Gets the company of this ImdbapiCompanyCredit.  # noqa: E501

        Company associated with the credit.  # noqa: E501

        :return: The company of this ImdbapiCompanyCredit.  # noqa: E501
        :rtype: ImdbapiCompany
        """
        return self._company

    @company.setter
    def company(self, company):
        """Sets the company of this ImdbapiCompanyCredit.

        Company associated with the credit.  # noqa: E501

        :param company: The company of this ImdbapiCompanyCredit.  # noqa: E501
        :type: ImdbapiCompany
        """

        self._company = company

    @property
    def category(self):
        """Gets the category of this ImdbapiCompanyCredit.  # noqa: E501

        Category of the company credit, such as production, sales, distribution, etc.  # noqa: E501

        :return: The category of this ImdbapiCompanyCredit.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this ImdbapiCompanyCredit.

        Category of the company credit, such as production, sales, distribution, etc.  # noqa: E501

        :param category: The category of this ImdbapiCompanyCredit.  # noqa: E501
        :type: str
        """

        self._category = category

    @property
    def countries(self):
        """Gets the countries of this ImdbapiCompanyCredit.  # noqa: E501

        Countries where the company is based or operates.  # noqa: E501

        :return: The countries of this ImdbapiCompanyCredit.  # noqa: E501
        :rtype: list[ImdbapiCountry]
        """
        return self._countries

    @countries.setter
    def countries(self, countries):
        """Sets the countries of this ImdbapiCompanyCredit.

        Countries where the company is based or operates.  # noqa: E501

        :param countries: The countries of this ImdbapiCompanyCredit.  # noqa: E501
        :type: list[ImdbapiCountry]
        """

        self._countries = countries

    @property
    def years_involved(self):
        """Gets the years_involved of this ImdbapiCompanyCredit.  # noqa: E501

        YearsInvolved represents the years a company was involved in a project.  # noqa: E501

        :return: The years_involved of this ImdbapiCompanyCredit.  # noqa: E501
        :rtype: ImdbapiYearsInvolved
        """
        return self._years_involved

    @years_involved.setter
    def years_involved(self, years_involved):
        """Sets the years_involved of this ImdbapiCompanyCredit.

        YearsInvolved represents the years a company was involved in a project.  # noqa: E501

        :param years_involved: The years_involved of this ImdbapiCompanyCredit.  # noqa: E501
        :type: ImdbapiYearsInvolved
        """

        self._years_involved = years_involved

    @property
    def attributes(self):
        """Gets the attributes of this ImdbapiCompanyCredit.  # noqa: E501


        :return: The attributes of this ImdbapiCompanyCredit.  # noqa: E501
        :rtype: list[str]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this ImdbapiCompanyCredit.


        :param attributes: The attributes of this ImdbapiCompanyCredit.  # noqa: E501
        :type: list[str]
        """

        self._attributes = attributes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiCompanyCredit, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiCompanyCredit):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiCompanyCredit):
            return True

        return self.to_dict() != other.to_dict()
