# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiListTitleCertificatesResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'certificates': 'list[ImdbapiCertificate]',
        'total_count': 'int'
    }

    attribute_map = {
        'certificates': 'certificates',
        'total_count': 'totalCount'
    }

    def __init__(self, certificates=None, total_count=None, _configuration=None):  # noqa: E501
        """ImdbapiListTitleCertificatesResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._certificates = None
        self._total_count = None
        self.discriminator = None

        if certificates is not None:
            self.certificates = certificates
        if total_count is not None:
            self.total_count = total_count

    @property
    def certificates(self):
        """Gets the certificates of this ImdbapiListTitleCertificatesResponse.  # noqa: E501

        List of certificates associated with the title.  # noqa: E501

        :return: The certificates of this ImdbapiListTitleCertificatesResponse.  # noqa: E501
        :rtype: list[ImdbapiCertificate]
        """
        return self._certificates

    @certificates.setter
    def certificates(self, certificates):
        """Sets the certificates of this ImdbapiListTitleCertificatesResponse.

        List of certificates associated with the title.  # noqa: E501

        :param certificates: The certificates of this ImdbapiListTitleCertificatesResponse.  # noqa: E501
        :type: list[ImdbapiCertificate]
        """

        self._certificates = certificates

    @property
    def total_count(self):
        """Gets the total_count of this ImdbapiListTitleCertificatesResponse.  # noqa: E501

        Total count of certificates associated with the title.  # noqa: E501

        :return: The total_count of this ImdbapiListTitleCertificatesResponse.  # noqa: E501
        :rtype: int
        """
        return self._total_count

    @total_count.setter
    def total_count(self, total_count):
        """Sets the total_count of this ImdbapiListTitleCertificatesResponse.

        Total count of certificates associated with the title.  # noqa: E501

        :param total_count: The total_count of this ImdbapiListTitleCertificatesResponse.  # noqa: E501
        :type: int
        """

        self._total_count = total_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiListTitleCertificatesResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiListTitleCertificatesResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiListTitleCertificatesResponse):
            return True

        return self.to_dict() != other.to_dict()
