# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiOpeningWeekendGross(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'gross': 'ImdbapiMoney',
        'weekend_end_date': 'ImdbapiPrecisionDate'
    }

    attribute_map = {
        'gross': 'gross',
        'weekend_end_date': 'weekendEndDate'
    }

    def __init__(self, gross=None, weekend_end_date=None, _configuration=None):  # noqa: E501
        """ImdbapiOpeningWeekendGross - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._gross = None
        self._weekend_end_date = None
        self.discriminator = None

        if gross is not None:
            self.gross = gross
        if weekend_end_date is not None:
            self.weekend_end_date = weekend_end_date

    @property
    def gross(self):
        """Gets the gross of this ImdbapiOpeningWeekendGross.  # noqa: E501

        The amount of money made in the opening weekend.  # noqa: E501

        :return: The gross of this ImdbapiOpeningWeekendGross.  # noqa: E501
        :rtype: ImdbapiMoney
        """
        return self._gross

    @gross.setter
    def gross(self, gross):
        """Sets the gross of this ImdbapiOpeningWeekendGross.

        The amount of money made in the opening weekend.  # noqa: E501

        :param gross: The gross of this ImdbapiOpeningWeekendGross.  # noqa: E501
        :type: ImdbapiMoney
        """

        self._gross = gross

    @property
    def weekend_end_date(self):
        """Gets the weekend_end_date of this ImdbapiOpeningWeekendGross.  # noqa: E501

        The date of the opening weekend.  # noqa: E501

        :return: The weekend_end_date of this ImdbapiOpeningWeekendGross.  # noqa: E501
        :rtype: ImdbapiPrecisionDate
        """
        return self._weekend_end_date

    @weekend_end_date.setter
    def weekend_end_date(self, weekend_end_date):
        """Sets the weekend_end_date of this ImdbapiOpeningWeekendGross.

        The date of the opening weekend.  # noqa: E501

        :param weekend_end_date: The weekend_end_date of this ImdbapiOpeningWeekendGross.  # noqa: E501
        :type: ImdbapiPrecisionDate
        """

        self._weekend_end_date = weekend_end_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiOpeningWeekendGross, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiOpeningWeekendGross):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiOpeningWeekendGross):
            return True

        return self.to_dict() != other.to_dict()
