# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiCertificate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'rating': 'str',
        'country': 'ImdbapiCountry',
        'attributes': 'list[str]'
    }

    attribute_map = {
        'rating': 'rating',
        'country': 'country',
        'attributes': 'attributes'
    }

    def __init__(self, rating=None, country=None, attributes=None, _configuration=None):  # noqa: E501
        """ImdbapiCertificate - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._rating = None
        self._country = None
        self._attributes = None
        self.discriminator = None

        if rating is not None:
            self.rating = rating
        if country is not None:
            self.country = country
        if attributes is not None:
            self.attributes = attributes

    @property
    def rating(self):
        """Gets the rating of this ImdbapiCertificate.  # noqa: E501

        The rating of the certificate, such as \"PG-13\", \"R\", etc.  # noqa: E501

        :return: The rating of this ImdbapiCertificate.  # noqa: E501
        :rtype: str
        """
        return self._rating

    @rating.setter
    def rating(self, rating):
        """Sets the rating of this ImdbapiCertificate.

        The rating of the certificate, such as \"PG-13\", \"R\", etc.  # noqa: E501

        :param rating: The rating of this ImdbapiCertificate.  # noqa: E501
        :type: str
        """

        self._rating = rating

    @property
    def country(self):
        """Gets the country of this ImdbapiCertificate.  # noqa: E501

        The country where this certificate is issued.  # noqa: E501

        :return: The country of this ImdbapiCertificate.  # noqa: E501
        :rtype: ImdbapiCountry
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this ImdbapiCertificate.

        The country where this certificate is issued.  # noqa: E501

        :param country: The country of this ImdbapiCertificate.  # noqa: E501
        :type: ImdbapiCountry
        """

        self._country = country

    @property
    def attributes(self):
        """Gets the attributes of this ImdbapiCertificate.  # noqa: E501


        :return: The attributes of this ImdbapiCertificate.  # noqa: E501
        :rtype: list[str]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this ImdbapiCertificate.


        :param attributes: The attributes of this ImdbapiCertificate.  # noqa: E501
        :type: list[str]
        """

        self._attributes = attributes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiCertificate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiCertificate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiCertificate):
            return True

        return self.to_dict() != other.to_dict()
