# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiInterest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'primary_image': 'ImdbapiImage',
        'description': 'str',
        'is_subgenre': 'bool',
        'similar_interests': 'list[ImdbapiInterest]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'primary_image': 'primaryImage',
        'description': 'description',
        'is_subgenre': 'isSubgenre',
        'similar_interests': 'similarInterests'
    }

    def __init__(self, id=None, name=None, primary_image=None, description=None, is_subgenre=None, similar_interests=None, _configuration=None):  # noqa: E501
        """ImdbapiInterest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._name = None
        self._primary_image = None
        self._description = None
        self._is_subgenre = None
        self._similar_interests = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if primary_image is not None:
            self.primary_image = primary_image
        if description is not None:
            self.description = description
        if is_subgenre is not None:
            self.is_subgenre = is_subgenre
        if similar_interests is not None:
            self.similar_interests = similar_interests

    @property
    def id(self):
        """Gets the id of this ImdbapiInterest.  # noqa: E501

        Unique identifier for the interest.  # noqa: E501

        :return: The id of this ImdbapiInterest.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ImdbapiInterest.

        Unique identifier for the interest.  # noqa: E501

        :param id: The id of this ImdbapiInterest.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ImdbapiInterest.  # noqa: E501

        The name of the interest, e.g., \"Action\", \"Action Epic\", \"Adult Animation\", etc.  # noqa: E501

        :return: The name of this ImdbapiInterest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ImdbapiInterest.

        The name of the interest, e.g., \"Action\", \"Action Epic\", \"Adult Animation\", etc.  # noqa: E501

        :param name: The name of this ImdbapiInterest.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def primary_image(self):
        """Gets the primary_image of this ImdbapiInterest.  # noqa: E501

        The primary image of the interest, which can be a poster or cover image.  # noqa: E501

        :return: The primary_image of this ImdbapiInterest.  # noqa: E501
        :rtype: ImdbapiImage
        """
        return self._primary_image

    @primary_image.setter
    def primary_image(self, primary_image):
        """Sets the primary_image of this ImdbapiInterest.

        The primary image of the interest, which can be a poster or cover image.  # noqa: E501

        :param primary_image: The primary_image of this ImdbapiInterest.  # noqa: E501
        :type: ImdbapiImage
        """

        self._primary_image = primary_image

    @property
    def description(self):
        """Gets the description of this ImdbapiInterest.  # noqa: E501

        A brief description of the interest, which can include details about the genre or type.  # noqa: E501

        :return: The description of this ImdbapiInterest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ImdbapiInterest.

        A brief description of the interest, which can include details about the genre or type.  # noqa: E501

        :param description: The description of this ImdbapiInterest.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def is_subgenre(self):
        """Gets the is_subgenre of this ImdbapiInterest.  # noqa: E501

        Indicates whether the interest is a subgenre of another genre.  # noqa: E501

        :return: The is_subgenre of this ImdbapiInterest.  # noqa: E501
        :rtype: bool
        """
        return self._is_subgenre

    @is_subgenre.setter
    def is_subgenre(self, is_subgenre):
        """Sets the is_subgenre of this ImdbapiInterest.

        Indicates whether the interest is a subgenre of another genre.  # noqa: E501

        :param is_subgenre: The is_subgenre of this ImdbapiInterest.  # noqa: E501
        :type: bool
        """

        self._is_subgenre = is_subgenre

    @property
    def similar_interests(self):
        """Gets the similar_interests of this ImdbapiInterest.  # noqa: E501

        A list of similar interests that are related to this interest.  # noqa: E501

        :return: The similar_interests of this ImdbapiInterest.  # noqa: E501
        :rtype: list[ImdbapiInterest]
        """
        return self._similar_interests

    @similar_interests.setter
    def similar_interests(self, similar_interests):
        """Sets the similar_interests of this ImdbapiInterest.

        A list of similar interests that are related to this interest.  # noqa: E501

        :param similar_interests: The similar_interests of this ImdbapiInterest.  # noqa: E501
        :type: list[ImdbapiInterest]
        """

        self._similar_interests = similar_interests

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiInterest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiInterest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiInterest):
            return True

        return self.to_dict() != other.to_dict()
