# coding: utf-8

"""
    IMDbAPI

    This is beta version of the IMDb API. It is not yet stable and may change in the future.  # noqa: E501

    OpenAPI spec version: 2.0.2-beta
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiListNameKnownForResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'known_for': 'list[ImdbapiCredit]',
        'next_page_token': 'str'
    }

    attribute_map = {
        'known_for': 'known_for',
        'next_page_token': 'next_page_token'
    }

    def __init__(self, known_for=None, next_page_token=None, _configuration=None):  # noqa: E501
        """ImdbapiListNameKnownForResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._known_for = None
        self._next_page_token = None
        self.discriminator = None

        if known_for is not None:
            self.known_for = known_for
        if next_page_token is not None:
            self.next_page_token = next_page_token

    @property
    def known_for(self):
        """Gets the known_for of this ImdbapiListNameKnownForResponse.  # noqa: E501

        List of \"known for\" credits associated with the name.  # noqa: E501

        :return: The known_for of this ImdbapiListNameKnownForResponse.  # noqa: E501
        :rtype: list[ImdbapiCredit]
        """
        return self._known_for

    @known_for.setter
    def known_for(self, known_for):
        """Sets the known_for of this ImdbapiListNameKnownForResponse.

        List of \"known for\" credits associated with the name.  # noqa: E501

        :param known_for: The known_for of this ImdbapiListNameKnownForResponse.  # noqa: E501
        :type: list[ImdbapiCredit]
        """

        self._known_for = known_for

    @property
    def next_page_token(self):
        """Gets the next_page_token of this ImdbapiListNameKnownForResponse.  # noqa: E501

        Optional. Token for the next page of results, if applicable.  # noqa: E501

        :return: The next_page_token of this ImdbapiListNameKnownForResponse.  # noqa: E501
        :rtype: str
        """
        return self._next_page_token

    @next_page_token.setter
    def next_page_token(self, next_page_token):
        """Sets the next_page_token of this ImdbapiListNameKnownForResponse.

        Optional. Token for the next page of results, if applicable.  # noqa: E501

        :param next_page_token: The next_page_token of this ImdbapiListNameKnownForResponse.  # noqa: E501
        :type: str
        """

        self._next_page_token = next_page_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiListNameKnownForResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiListNameKnownForResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiListNameKnownForResponse):
            return True

        return self.to_dict() != other.to_dict()
