# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiAwardNomination(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'titles': 'list[ImdbapiTitle]',
        'nominees': 'list[ImdbapiName]',
        'event': 'ImdbapiEvent',
        'year': 'int',
        'text': 'str',
        'category': 'str',
        'is_winner': 'bool',
        'winner_rank': 'int'
    }

    attribute_map = {
        'titles': 'titles',
        'nominees': 'nominees',
        'event': 'event',
        'year': 'year',
        'text': 'text',
        'category': 'category',
        'is_winner': 'isWinner',
        'winner_rank': 'winnerRank'
    }

    def __init__(self, titles=None, nominees=None, event=None, year=None, text=None, category=None, is_winner=None, winner_rank=None, _configuration=None):  # noqa: E501
        """ImdbapiAwardNomination - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._titles = None
        self._nominees = None
        self._event = None
        self._year = None
        self._text = None
        self._category = None
        self._is_winner = None
        self._winner_rank = None
        self.discriminator = None

        if titles is not None:
            self.titles = titles
        if nominees is not None:
            self.nominees = nominees
        if event is not None:
            self.event = event
        if year is not None:
            self.year = year
        if text is not None:
            self.text = text
        if category is not None:
            self.category = category
        if is_winner is not None:
            self.is_winner = is_winner
        if winner_rank is not None:
            self.winner_rank = winner_rank

    @property
    def titles(self):
        """Gets the titles of this ImdbapiAwardNomination.  # noqa: E501

        The titles associated with the award nomination.  # noqa: E501

        :return: The titles of this ImdbapiAwardNomination.  # noqa: E501
        :rtype: list[ImdbapiTitle]
        """
        return self._titles

    @titles.setter
    def titles(self, titles):
        """Sets the titles of this ImdbapiAwardNomination.

        The titles associated with the award nomination.  # noqa: E501

        :param titles: The titles of this ImdbapiAwardNomination.  # noqa: E501
        :type: list[ImdbapiTitle]
        """

        self._titles = titles

    @property
    def nominees(self):
        """Gets the nominees of this ImdbapiAwardNomination.  # noqa: E501

        The nominees associated with the award nomination.  # noqa: E501

        :return: The nominees of this ImdbapiAwardNomination.  # noqa: E501
        :rtype: list[ImdbapiName]
        """
        return self._nominees

    @nominees.setter
    def nominees(self, nominees):
        """Sets the nominees of this ImdbapiAwardNomination.

        The nominees associated with the award nomination.  # noqa: E501

        :param nominees: The nominees of this ImdbapiAwardNomination.  # noqa: E501
        :type: list[ImdbapiName]
        """

        self._nominees = nominees

    @property
    def event(self):
        """Gets the event of this ImdbapiAwardNomination.  # noqa: E501

        The event associated with the award nomination.  # noqa: E501

        :return: The event of this ImdbapiAwardNomination.  # noqa: E501
        :rtype: ImdbapiEvent
        """
        return self._event

    @event.setter
    def event(self, event):
        """Sets the event of this ImdbapiAwardNomination.

        The event associated with the award nomination.  # noqa: E501

        :param event: The event of this ImdbapiAwardNomination.  # noqa: E501
        :type: ImdbapiEvent
        """

        self._event = event

    @property
    def year(self):
        """Gets the year of this ImdbapiAwardNomination.  # noqa: E501

        The year of the award nomination.  # noqa: E501

        :return: The year of this ImdbapiAwardNomination.  # noqa: E501
        :rtype: int
        """
        return self._year

    @year.setter
    def year(self, year):
        """Sets the year of this ImdbapiAwardNomination.

        The year of the award nomination.  # noqa: E501

        :param year: The year of this ImdbapiAwardNomination.  # noqa: E501
        :type: int
        """

        self._year = year

    @property
    def text(self):
        """Gets the text of this ImdbapiAwardNomination.  # noqa: E501

        The text description of the award nomination.  # noqa: E501

        :return: The text of this ImdbapiAwardNomination.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this ImdbapiAwardNomination.

        The text description of the award nomination.  # noqa: E501

        :param text: The text of this ImdbapiAwardNomination.  # noqa: E501
        :type: str
        """

        self._text = text

    @property
    def category(self):
        """Gets the category of this ImdbapiAwardNomination.  # noqa: E501

        The category of the award nomination.  # noqa: E501

        :return: The category of this ImdbapiAwardNomination.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this ImdbapiAwardNomination.

        The category of the award nomination.  # noqa: E501

        :param category: The category of this ImdbapiAwardNomination.  # noqa: E501
        :type: str
        """

        self._category = category

    @property
    def is_winner(self):
        """Gets the is_winner of this ImdbapiAwardNomination.  # noqa: E501

        Whether the nomination is a winner.  # noqa: E501

        :return: The is_winner of this ImdbapiAwardNomination.  # noqa: E501
        :rtype: bool
        """
        return self._is_winner

    @is_winner.setter
    def is_winner(self, is_winner):
        """Sets the is_winner of this ImdbapiAwardNomination.

        Whether the nomination is a winner.  # noqa: E501

        :param is_winner: The is_winner of this ImdbapiAwardNomination.  # noqa: E501
        :type: bool
        """

        self._is_winner = is_winner

    @property
    def winner_rank(self):
        """Gets the winner_rank of this ImdbapiAwardNomination.  # noqa: E501

        The rank of the winner in the nomination.  # noqa: E501

        :return: The winner_rank of this ImdbapiAwardNomination.  # noqa: E501
        :rtype: int
        """
        return self._winner_rank

    @winner_rank.setter
    def winner_rank(self, winner_rank):
        """Sets the winner_rank of this ImdbapiAwardNomination.

        The rank of the winner in the nomination.  # noqa: E501

        :param winner_rank: The winner_rank of this ImdbapiAwardNomination.  # noqa: E501
        :type: int
        """

        self._winner_rank = winner_rank

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiAwardNomination, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiAwardNomination):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiAwardNomination):
            return True

        return self.to_dict() != other.to_dict()
