# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiParentsGuideSeverity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'severity_level': 'str',
        'vote_count': 'int'
    }

    attribute_map = {
        'severity_level': 'severityLevel',
        'vote_count': 'voteCount'
    }

    def __init__(self, severity_level=None, vote_count=None, _configuration=None):  # noqa: E501
        """ImdbapiParentsGuideSeverity - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._severity_level = None
        self._vote_count = None
        self.discriminator = None

        if severity_level is not None:
            self.severity_level = severity_level
        if vote_count is not None:
            self.vote_count = vote_count

    @property
    def severity_level(self):
        """Gets the severity_level of this ImdbapiParentsGuideSeverity.  # noqa: E501


        :return: The severity_level of this ImdbapiParentsGuideSeverity.  # noqa: E501
        :rtype: str
        """
        return self._severity_level

    @severity_level.setter
    def severity_level(self, severity_level):
        """Sets the severity_level of this ImdbapiParentsGuideSeverity.


        :param severity_level: The severity_level of this ImdbapiParentsGuideSeverity.  # noqa: E501
        :type: str
        """

        self._severity_level = severity_level

    @property
    def vote_count(self):
        """Gets the vote_count of this ImdbapiParentsGuideSeverity.  # noqa: E501


        :return: The vote_count of this ImdbapiParentsGuideSeverity.  # noqa: E501
        :rtype: int
        """
        return self._vote_count

    @vote_count.setter
    def vote_count(self, vote_count):
        """Sets the vote_count of this ImdbapiParentsGuideSeverity.


        :param vote_count: The vote_count of this ImdbapiParentsGuideSeverity.  # noqa: E501
        :type: int
        """

        self._vote_count = vote_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiParentsGuideSeverity, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiParentsGuideSeverity):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiParentsGuideSeverity):
            return True

        return self.to_dict() != other.to_dict()
