# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiNameTrivia(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'text': 'str',
        'interest_count': 'int',
        'vote_count': 'int'
    }

    attribute_map = {
        'id': 'id',
        'text': 'text',
        'interest_count': 'interestCount',
        'vote_count': 'voteCount'
    }

    def __init__(self, id=None, text=None, interest_count=None, vote_count=None, _configuration=None):  # noqa: E501
        """ImdbapiNameTrivia - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._text = None
        self._interest_count = None
        self._vote_count = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if text is not None:
            self.text = text
        if interest_count is not None:
            self.interest_count = interest_count
        if vote_count is not None:
            self.vote_count = vote_count

    @property
    def id(self):
        """Gets the id of this ImdbapiNameTrivia.  # noqa: E501

        The unique identifier for the trivia.  # noqa: E501

        :return: The id of this ImdbapiNameTrivia.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ImdbapiNameTrivia.

        The unique identifier for the trivia.  # noqa: E501

        :param id: The id of this ImdbapiNameTrivia.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def text(self):
        """Gets the text of this ImdbapiNameTrivia.  # noqa: E501

        The trivia body text.  # noqa: E501

        :return: The text of this ImdbapiNameTrivia.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this ImdbapiNameTrivia.

        The trivia body text.  # noqa: E501

        :param text: The text of this ImdbapiNameTrivia.  # noqa: E501
        :type: str
        """

        self._text = text

    @property
    def interest_count(self):
        """Gets the interest_count of this ImdbapiNameTrivia.  # noqa: E501

        The number of users who have expressed interest in this trivia.  # noqa: E501

        :return: The interest_count of this ImdbapiNameTrivia.  # noqa: E501
        :rtype: int
        """
        return self._interest_count

    @interest_count.setter
    def interest_count(self, interest_count):
        """Sets the interest_count of this ImdbapiNameTrivia.

        The number of users who have expressed interest in this trivia.  # noqa: E501

        :param interest_count: The interest_count of this ImdbapiNameTrivia.  # noqa: E501
        :type: int
        """

        self._interest_count = interest_count

    @property
    def vote_count(self):
        """Gets the vote_count of this ImdbapiNameTrivia.  # noqa: E501

        The number of votes this trivia has received.  # noqa: E501

        :return: The vote_count of this ImdbapiNameTrivia.  # noqa: E501
        :rtype: int
        """
        return self._vote_count

    @vote_count.setter
    def vote_count(self, vote_count):
        """Sets the vote_count of this ImdbapiNameTrivia.

        The number of votes this trivia has received.  # noqa: E501

        :param vote_count: The vote_count of this ImdbapiNameTrivia.  # noqa: E501
        :type: int
        """

        self._vote_count = vote_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiNameTrivia, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiNameTrivia):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiNameTrivia):
            return True

        return self.to_dict() != other.to_dict()
