# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiVideo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'type': 'str',
        'name': 'str',
        'primary_image': 'ImdbapiImage',
        'description': 'str',
        'width': 'int',
        'height': 'int',
        'runtime_seconds': 'int'
    }

    attribute_map = {
        'id': 'id',
        'type': 'type',
        'name': 'name',
        'primary_image': 'primaryImage',
        'description': 'description',
        'width': 'width',
        'height': 'height',
        'runtime_seconds': 'runtimeSeconds'
    }

    def __init__(self, id=None, type=None, name=None, primary_image=None, description=None, width=None, height=None, runtime_seconds=None, _configuration=None):  # noqa: E501
        """ImdbapiVideo - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._type = None
        self._name = None
        self._primary_image = None
        self._description = None
        self._width = None
        self._height = None
        self._runtime_seconds = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if type is not None:
            self.type = type
        if name is not None:
            self.name = name
        if primary_image is not None:
            self.primary_image = primary_image
        if description is not None:
            self.description = description
        if width is not None:
            self.width = width
        if height is not None:
            self.height = height
        if runtime_seconds is not None:
            self.runtime_seconds = runtime_seconds

    @property
    def id(self):
        """Gets the id of this ImdbapiVideo.  # noqa: E501

        The unique identifier for the video.  # noqa: E501

        :return: The id of this ImdbapiVideo.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ImdbapiVideo.

        The unique identifier for the video.  # noqa: E501

        :param id: The id of this ImdbapiVideo.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def type(self):
        """Gets the type of this ImdbapiVideo.  # noqa: E501

        The type of the video.  # noqa: E501

        :return: The type of this ImdbapiVideo.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ImdbapiVideo.

        The type of the video.  # noqa: E501

        :param type: The type of this ImdbapiVideo.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def name(self):
        """Gets the name of this ImdbapiVideo.  # noqa: E501

        The name of the video.  # noqa: E501

        :return: The name of this ImdbapiVideo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ImdbapiVideo.

        The name of the video.  # noqa: E501

        :param name: The name of this ImdbapiVideo.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def primary_image(self):
        """Gets the primary_image of this ImdbapiVideo.  # noqa: E501

        The primary image of the video.  # noqa: E501

        :return: The primary_image of this ImdbapiVideo.  # noqa: E501
        :rtype: ImdbapiImage
        """
        return self._primary_image

    @primary_image.setter
    def primary_image(self, primary_image):
        """Sets the primary_image of this ImdbapiVideo.

        The primary image of the video.  # noqa: E501

        :param primary_image: The primary_image of this ImdbapiVideo.  # noqa: E501
        :type: ImdbapiImage
        """

        self._primary_image = primary_image

    @property
    def description(self):
        """Gets the description of this ImdbapiVideo.  # noqa: E501

        A description of the video.  # noqa: E501

        :return: The description of this ImdbapiVideo.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ImdbapiVideo.

        A description of the video.  # noqa: E501

        :param description: The description of this ImdbapiVideo.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def width(self):
        """Gets the width of this ImdbapiVideo.  # noqa: E501

        The width of the video in pixels.  # noqa: E501

        :return: The width of this ImdbapiVideo.  # noqa: E501
        :rtype: int
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this ImdbapiVideo.

        The width of the video in pixels.  # noqa: E501

        :param width: The width of this ImdbapiVideo.  # noqa: E501
        :type: int
        """

        self._width = width

    @property
    def height(self):
        """Gets the height of this ImdbapiVideo.  # noqa: E501

        The height of the video in pixels.  # noqa: E501

        :return: The height of this ImdbapiVideo.  # noqa: E501
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this ImdbapiVideo.

        The height of the video in pixels.  # noqa: E501

        :param height: The height of this ImdbapiVideo.  # noqa: E501
        :type: int
        """

        self._height = height

    @property
    def runtime_seconds(self):
        """Gets the runtime_seconds of this ImdbapiVideo.  # noqa: E501

        The runtime of the video in seconds.  # noqa: E501

        :return: The runtime_seconds of this ImdbapiVideo.  # noqa: E501
        :rtype: int
        """
        return self._runtime_seconds

    @runtime_seconds.setter
    def runtime_seconds(self, runtime_seconds):
        """Sets the runtime_seconds of this ImdbapiVideo.

        The runtime of the video in seconds.  # noqa: E501

        :param runtime_seconds: The runtime_seconds of this ImdbapiVideo.  # noqa: E501
        :type: int
        """

        self._runtime_seconds = runtime_seconds

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiVideo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiVideo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiVideo):
            return True

        return self.to_dict() != other.to_dict()
