# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiListTitleEpisodesResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'episodes': 'list[ImdbapiEpisode]',
        'total_count': 'int',
        'next_page_token': 'str'
    }

    attribute_map = {
        'episodes': 'episodes',
        'total_count': 'totalCount',
        'next_page_token': 'nextPageToken'
    }

    def __init__(self, episodes=None, total_count=None, next_page_token=None, _configuration=None):  # noqa: E501
        """ImdbapiListTitleEpisodesResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._episodes = None
        self._total_count = None
        self._next_page_token = None
        self.discriminator = None

        if episodes is not None:
            self.episodes = episodes
        if total_count is not None:
            self.total_count = total_count
        if next_page_token is not None:
            self.next_page_token = next_page_token

    @property
    def episodes(self):
        """Gets the episodes of this ImdbapiListTitleEpisodesResponse.  # noqa: E501

        List of episodes associated with the title.  # noqa: E501

        :return: The episodes of this ImdbapiListTitleEpisodesResponse.  # noqa: E501
        :rtype: list[ImdbapiEpisode]
        """
        return self._episodes

    @episodes.setter
    def episodes(self, episodes):
        """Sets the episodes of this ImdbapiListTitleEpisodesResponse.

        List of episodes associated with the title.  # noqa: E501

        :param episodes: The episodes of this ImdbapiListTitleEpisodesResponse.  # noqa: E501
        :type: list[ImdbapiEpisode]
        """

        self._episodes = episodes

    @property
    def total_count(self):
        """Gets the total_count of this ImdbapiListTitleEpisodesResponse.  # noqa: E501

        The total number of episodes that have aired for this title.  # noqa: E501

        :return: The total_count of this ImdbapiListTitleEpisodesResponse.  # noqa: E501
        :rtype: int
        """
        return self._total_count

    @total_count.setter
    def total_count(self, total_count):
        """Sets the total_count of this ImdbapiListTitleEpisodesResponse.

        The total number of episodes that have aired for this title.  # noqa: E501

        :param total_count: The total_count of this ImdbapiListTitleEpisodesResponse.  # noqa: E501
        :type: int
        """

        self._total_count = total_count

    @property
    def next_page_token(self):
        """Gets the next_page_token of this ImdbapiListTitleEpisodesResponse.  # noqa: E501

        Token for the next page of results, if applicable.  # noqa: E501

        :return: The next_page_token of this ImdbapiListTitleEpisodesResponse.  # noqa: E501
        :rtype: str
        """
        return self._next_page_token

    @next_page_token.setter
    def next_page_token(self, next_page_token):
        """Sets the next_page_token of this ImdbapiListTitleEpisodesResponse.

        Token for the next page of results, if applicable.  # noqa: E501

        :param next_page_token: The next_page_token of this ImdbapiListTitleEpisodesResponse.  # noqa: E501
        :type: str
        """

        self._next_page_token = next_page_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiListTitleEpisodesResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiListTitleEpisodesResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiListTitleEpisodesResponse):
            return True

        return self.to_dict() != other.to_dict()
