# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiNameMeterRanking(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'current_rank': 'int',
        'change_direction': 'str',
        'difference': 'int'
    }

    attribute_map = {
        'current_rank': 'currentRank',
        'change_direction': 'changeDirection',
        'difference': 'difference'
    }

    def __init__(self, current_rank=None, change_direction=None, difference=None, _configuration=None):  # noqa: E501
        """ImdbapiNameMeterRanking - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._current_rank = None
        self._change_direction = None
        self._difference = None
        self.discriminator = None

        if current_rank is not None:
            self.current_rank = current_rank
        if change_direction is not None:
            self.change_direction = change_direction
        if difference is not None:
            self.difference = difference

    @property
    def current_rank(self):
        """Gets the current_rank of this ImdbapiNameMeterRanking.  # noqa: E501

        The current rank of the person in the IMDb popularity meter.  # noqa: E501

        :return: The current_rank of this ImdbapiNameMeterRanking.  # noqa: E501
        :rtype: int
        """
        return self._current_rank

    @current_rank.setter
    def current_rank(self, current_rank):
        """Sets the current_rank of this ImdbapiNameMeterRanking.

        The current rank of the person in the IMDb popularity meter.  # noqa: E501

        :param current_rank: The current_rank of this ImdbapiNameMeterRanking.  # noqa: E501
        :type: int
        """

        self._current_rank = current_rank

    @property
    def change_direction(self):
        """Gets the change_direction of this ImdbapiNameMeterRanking.  # noqa: E501

        The direction of the change in rank, which can be \"UP\", \"DOWN\", or \"none\".  # noqa: E501

        :return: The change_direction of this ImdbapiNameMeterRanking.  # noqa: E501
        :rtype: str
        """
        return self._change_direction

    @change_direction.setter
    def change_direction(self, change_direction):
        """Sets the change_direction of this ImdbapiNameMeterRanking.

        The direction of the change in rank, which can be \"UP\", \"DOWN\", or \"none\".  # noqa: E501

        :param change_direction: The change_direction of this ImdbapiNameMeterRanking.  # noqa: E501
        :type: str
        """

        self._change_direction = change_direction

    @property
    def difference(self):
        """Gets the difference of this ImdbapiNameMeterRanking.  # noqa: E501

        The difference in rank compared to the previous measurement. Positive for an increase, negative for a decrease, and zero for no change.  # noqa: E501

        :return: The difference of this ImdbapiNameMeterRanking.  # noqa: E501
        :rtype: int
        """
        return self._difference

    @difference.setter
    def difference(self, difference):
        """Sets the difference of this ImdbapiNameMeterRanking.

        The difference in rank compared to the previous measurement. Positive for an increase, negative for a decrease, and zero for no change.  # noqa: E501

        :param difference: The difference of this ImdbapiNameMeterRanking.  # noqa: E501
        :type: int
        """

        self._difference = difference

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiNameMeterRanking, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiNameMeterRanking):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiNameMeterRanking):
            return True

        return self.to_dict() != other.to_dict()
