# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiListTitleReleaseDatesResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'release_dates': 'list[ImdbapiReleaseDate]',
        'next_page_token': 'str'
    }

    attribute_map = {
        'release_dates': 'releaseDates',
        'next_page_token': 'nextPageToken'
    }

    def __init__(self, release_dates=None, next_page_token=None, _configuration=None):  # noqa: E501
        """ImdbapiListTitleReleaseDatesResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._release_dates = None
        self._next_page_token = None
        self.discriminator = None

        if release_dates is not None:
            self.release_dates = release_dates
        if next_page_token is not None:
            self.next_page_token = next_page_token

    @property
    def release_dates(self):
        """Gets the release_dates of this ImdbapiListTitleReleaseDatesResponse.  # noqa: E501

        List of release dates associated with the title.  # noqa: E501

        :return: The release_dates of this ImdbapiListTitleReleaseDatesResponse.  # noqa: E501
        :rtype: list[ImdbapiReleaseDate]
        """
        return self._release_dates

    @release_dates.setter
    def release_dates(self, release_dates):
        """Sets the release_dates of this ImdbapiListTitleReleaseDatesResponse.

        List of release dates associated with the title.  # noqa: E501

        :param release_dates: The release_dates of this ImdbapiListTitleReleaseDatesResponse.  # noqa: E501
        :type: list[ImdbapiReleaseDate]
        """

        self._release_dates = release_dates

    @property
    def next_page_token(self):
        """Gets the next_page_token of this ImdbapiListTitleReleaseDatesResponse.  # noqa: E501

        Token for the next page of results, if applicable.  # noqa: E501

        :return: The next_page_token of this ImdbapiListTitleReleaseDatesResponse.  # noqa: E501
        :rtype: str
        """
        return self._next_page_token

    @next_page_token.setter
    def next_page_token(self, next_page_token):
        """Sets the next_page_token of this ImdbapiListTitleReleaseDatesResponse.

        Token for the next page of results, if applicable.  # noqa: E501

        :param next_page_token: The next_page_token of this ImdbapiListTitleReleaseDatesResponse.  # noqa: E501
        :type: str
        """

        self._next_page_token = next_page_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiListTitleReleaseDatesResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiListTitleReleaseDatesResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiListTitleReleaseDatesResponse):
            return True

        return self.to_dict() != other.to_dict()
