# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiParentsGuide(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'category': 'ImdbapiParentsGuideCategory',
        'severity_breakdowns': 'list[ImdbapiParentsGuideSeverity]',
        'reviews': 'list[ImdbapiParentsGuideReview]'
    }

    attribute_map = {
        'category': 'category',
        'severity_breakdowns': 'severityBreakdowns',
        'reviews': 'reviews'
    }

    def __init__(self, category=None, severity_breakdowns=None, reviews=None, _configuration=None):  # noqa: E501
        """ImdbapiParentsGuide - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._category = None
        self._severity_breakdowns = None
        self._reviews = None
        self.discriminator = None

        if category is not None:
            self.category = category
        if severity_breakdowns is not None:
            self.severity_breakdowns = severity_breakdowns
        if reviews is not None:
            self.reviews = reviews

    @property
    def category(self):
        """Gets the category of this ImdbapiParentsGuide.  # noqa: E501


        :return: The category of this ImdbapiParentsGuide.  # noqa: E501
        :rtype: ImdbapiParentsGuideCategory
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this ImdbapiParentsGuide.


        :param category: The category of this ImdbapiParentsGuide.  # noqa: E501
        :type: ImdbapiParentsGuideCategory
        """

        self._category = category

    @property
    def severity_breakdowns(self):
        """Gets the severity_breakdowns of this ImdbapiParentsGuide.  # noqa: E501


        :return: The severity_breakdowns of this ImdbapiParentsGuide.  # noqa: E501
        :rtype: list[ImdbapiParentsGuideSeverity]
        """
        return self._severity_breakdowns

    @severity_breakdowns.setter
    def severity_breakdowns(self, severity_breakdowns):
        """Sets the severity_breakdowns of this ImdbapiParentsGuide.


        :param severity_breakdowns: The severity_breakdowns of this ImdbapiParentsGuide.  # noqa: E501
        :type: list[ImdbapiParentsGuideSeverity]
        """

        self._severity_breakdowns = severity_breakdowns

    @property
    def reviews(self):
        """Gets the reviews of this ImdbapiParentsGuide.  # noqa: E501


        :return: The reviews of this ImdbapiParentsGuide.  # noqa: E501
        :rtype: list[ImdbapiParentsGuideReview]
        """
        return self._reviews

    @reviews.setter
    def reviews(self, reviews):
        """Sets the reviews of this ImdbapiParentsGuide.


        :param reviews: The reviews of this ImdbapiParentsGuide.  # noqa: E501
        :type: list[ImdbapiParentsGuideReview]
        """

        self._reviews = reviews

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiParentsGuide, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiParentsGuide):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiParentsGuide):
            return True

        return self.to_dict() != other.to_dict()
