# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiYearsInvolved(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start_year': 'int',
        'end_year': 'int'
    }

    attribute_map = {
        'start_year': 'startYear',
        'end_year': 'endYear'
    }

    def __init__(self, start_year=None, end_year=None, _configuration=None):  # noqa: E501
        """ImdbapiYearsInvolved - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._start_year = None
        self._end_year = None
        self.discriminator = None

        if start_year is not None:
            self.start_year = start_year
        if end_year is not None:
            self.end_year = end_year

    @property
    def start_year(self):
        """Gets the start_year of this ImdbapiYearsInvolved.  # noqa: E501


        :return: The start_year of this ImdbapiYearsInvolved.  # noqa: E501
        :rtype: int
        """
        return self._start_year

    @start_year.setter
    def start_year(self, start_year):
        """Sets the start_year of this ImdbapiYearsInvolved.


        :param start_year: The start_year of this ImdbapiYearsInvolved.  # noqa: E501
        :type: int
        """

        self._start_year = start_year

    @property
    def end_year(self):
        """Gets the end_year of this ImdbapiYearsInvolved.  # noqa: E501


        :return: The end_year of this ImdbapiYearsInvolved.  # noqa: E501
        :rtype: int
        """
        return self._end_year

    @end_year.setter
    def end_year(self, end_year):
        """Sets the end_year of this ImdbapiYearsInvolved.


        :param end_year: The end_year of this ImdbapiYearsInvolved.  # noqa: E501
        :type: int
        """

        self._end_year = end_year

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiYearsInvolved, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiYearsInvolved):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiYearsInvolved):
            return True

        return self.to_dict() != other.to_dict()
