# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiImage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'url': 'str',
        'width': 'int',
        'height': 'int',
        'type': 'str'
    }

    attribute_map = {
        'url': 'url',
        'width': 'width',
        'height': 'height',
        'type': 'type'
    }

    def __init__(self, url=None, width=None, height=None, type=None, _configuration=None):  # noqa: E501
        """ImdbapiImage - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._url = None
        self._width = None
        self._height = None
        self._type = None
        self.discriminator = None

        if url is not None:
            self.url = url
        if width is not None:
            self.width = width
        if height is not None:
            self.height = height
        if type is not None:
            self.type = type

    @property
    def url(self):
        """Gets the url of this ImdbapiImage.  # noqa: E501

        The URL of the image, which can be used to access the image file.  # noqa: E501

        :return: The url of this ImdbapiImage.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this ImdbapiImage.

        The URL of the image, which can be used to access the image file.  # noqa: E501

        :param url: The url of this ImdbapiImage.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def width(self):
        """Gets the width of this ImdbapiImage.  # noqa: E501

        The width of the image in pixels.  # noqa: E501

        :return: The width of this ImdbapiImage.  # noqa: E501
        :rtype: int
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this ImdbapiImage.

        The width of the image in pixels.  # noqa: E501

        :param width: The width of this ImdbapiImage.  # noqa: E501
        :type: int
        """

        self._width = width

    @property
    def height(self):
        """Gets the height of this ImdbapiImage.  # noqa: E501

        The height of the image in pixels.  # noqa: E501

        :return: The height of this ImdbapiImage.  # noqa: E501
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this ImdbapiImage.

        The height of the image in pixels.  # noqa: E501

        :param height: The height of this ImdbapiImage.  # noqa: E501
        :type: int
        """

        self._height = height

    @property
    def type(self):
        """Gets the type of this ImdbapiImage.  # noqa: E501

        The type of the image, such as \"poster\", \"still_frame\", \"event\", etc.  # noqa: E501

        :return: The type of this ImdbapiImage.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ImdbapiImage.

        The type of the image, such as \"poster\", \"still_frame\", \"event\", etc.  # noqa: E501

        :param type: The type of this ImdbapiImage.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiImage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiImage):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiImage):
            return True

        return self.to_dict() != other.to_dict()
