# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiListTitleParentsGuideResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'parents_guide': 'list[ImdbapiParentsGuide]'
    }

    attribute_map = {
        'parents_guide': 'parentsGuide'
    }

    def __init__(self, parents_guide=None, _configuration=None):  # noqa: E501
        """ImdbapiListTitleParentsGuideResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._parents_guide = None
        self.discriminator = None

        if parents_guide is not None:
            self.parents_guide = parents_guide

    @property
    def parents_guide(self):
        """Gets the parents_guide of this ImdbapiListTitleParentsGuideResponse.  # noqa: E501

        List of parents guide entries associated with the title.  # noqa: E501

        :return: The parents_guide of this ImdbapiListTitleParentsGuideResponse.  # noqa: E501
        :rtype: list[ImdbapiParentsGuide]
        """
        return self._parents_guide

    @parents_guide.setter
    def parents_guide(self, parents_guide):
        """Sets the parents_guide of this ImdbapiListTitleParentsGuideResponse.

        List of parents guide entries associated with the title.  # noqa: E501

        :param parents_guide: The parents_guide of this ImdbapiListTitleParentsGuideResponse.  # noqa: E501
        :type: list[ImdbapiParentsGuide]
        """

        self._parents_guide = parents_guide

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiListTitleParentsGuideResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiListTitleParentsGuideResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiListTitleParentsGuideResponse):
            return True

        return self.to_dict() != other.to_dict()
