# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiEpisode(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'title': 'str',
        'primary_image': 'ImdbapiImage',
        'season': 'str',
        'episode_number': 'int',
        'runtime_seconds': 'int',
        'plot': 'str',
        'rating': 'ImdbapiRating',
        'release_date': 'ImdbapiPrecisionDate'
    }

    attribute_map = {
        'id': 'id',
        'title': 'title',
        'primary_image': 'primaryImage',
        'season': 'season',
        'episode_number': 'episodeNumber',
        'runtime_seconds': 'runtimeSeconds',
        'plot': 'plot',
        'rating': 'rating',
        'release_date': 'releaseDate'
    }

    def __init__(self, id=None, title=None, primary_image=None, season=None, episode_number=None, runtime_seconds=None, plot=None, rating=None, release_date=None, _configuration=None):  # noqa: E501
        """ImdbapiEpisode - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._title = None
        self._primary_image = None
        self._season = None
        self._episode_number = None
        self._runtime_seconds = None
        self._plot = None
        self._rating = None
        self._release_date = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if title is not None:
            self.title = title
        if primary_image is not None:
            self.primary_image = primary_image
        if season is not None:
            self.season = season
        if episode_number is not None:
            self.episode_number = episode_number
        if runtime_seconds is not None:
            self.runtime_seconds = runtime_seconds
        if plot is not None:
            self.plot = plot
        if rating is not None:
            self.rating = rating
        if release_date is not None:
            self.release_date = release_date

    @property
    def id(self):
        """Gets the id of this ImdbapiEpisode.  # noqa: E501


        :return: The id of this ImdbapiEpisode.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ImdbapiEpisode.


        :param id: The id of this ImdbapiEpisode.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def title(self):
        """Gets the title of this ImdbapiEpisode.  # noqa: E501


        :return: The title of this ImdbapiEpisode.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this ImdbapiEpisode.


        :param title: The title of this ImdbapiEpisode.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def primary_image(self):
        """Gets the primary_image of this ImdbapiEpisode.  # noqa: E501


        :return: The primary_image of this ImdbapiEpisode.  # noqa: E501
        :rtype: ImdbapiImage
        """
        return self._primary_image

    @primary_image.setter
    def primary_image(self, primary_image):
        """Sets the primary_image of this ImdbapiEpisode.


        :param primary_image: The primary_image of this ImdbapiEpisode.  # noqa: E501
        :type: ImdbapiImage
        """

        self._primary_image = primary_image

    @property
    def season(self):
        """Gets the season of this ImdbapiEpisode.  # noqa: E501


        :return: The season of this ImdbapiEpisode.  # noqa: E501
        :rtype: str
        """
        return self._season

    @season.setter
    def season(self, season):
        """Sets the season of this ImdbapiEpisode.


        :param season: The season of this ImdbapiEpisode.  # noqa: E501
        :type: str
        """

        self._season = season

    @property
    def episode_number(self):
        """Gets the episode_number of this ImdbapiEpisode.  # noqa: E501


        :return: The episode_number of this ImdbapiEpisode.  # noqa: E501
        :rtype: int
        """
        return self._episode_number

    @episode_number.setter
    def episode_number(self, episode_number):
        """Sets the episode_number of this ImdbapiEpisode.


        :param episode_number: The episode_number of this ImdbapiEpisode.  # noqa: E501
        :type: int
        """

        self._episode_number = episode_number

    @property
    def runtime_seconds(self):
        """Gets the runtime_seconds of this ImdbapiEpisode.  # noqa: E501


        :return: The runtime_seconds of this ImdbapiEpisode.  # noqa: E501
        :rtype: int
        """
        return self._runtime_seconds

    @runtime_seconds.setter
    def runtime_seconds(self, runtime_seconds):
        """Sets the runtime_seconds of this ImdbapiEpisode.


        :param runtime_seconds: The runtime_seconds of this ImdbapiEpisode.  # noqa: E501
        :type: int
        """

        self._runtime_seconds = runtime_seconds

    @property
    def plot(self):
        """Gets the plot of this ImdbapiEpisode.  # noqa: E501


        :return: The plot of this ImdbapiEpisode.  # noqa: E501
        :rtype: str
        """
        return self._plot

    @plot.setter
    def plot(self, plot):
        """Sets the plot of this ImdbapiEpisode.


        :param plot: The plot of this ImdbapiEpisode.  # noqa: E501
        :type: str
        """

        self._plot = plot

    @property
    def rating(self):
        """Gets the rating of this ImdbapiEpisode.  # noqa: E501


        :return: The rating of this ImdbapiEpisode.  # noqa: E501
        :rtype: ImdbapiRating
        """
        return self._rating

    @rating.setter
    def rating(self, rating):
        """Sets the rating of this ImdbapiEpisode.


        :param rating: The rating of this ImdbapiEpisode.  # noqa: E501
        :type: ImdbapiRating
        """

        self._rating = rating

    @property
    def release_date(self):
        """Gets the release_date of this ImdbapiEpisode.  # noqa: E501


        :return: The release_date of this ImdbapiEpisode.  # noqa: E501
        :rtype: ImdbapiPrecisionDate
        """
        return self._release_date

    @release_date.setter
    def release_date(self, release_date):
        """Sets the release_date of this ImdbapiEpisode.


        :param release_date: The release_date of this ImdbapiEpisode.  # noqa: E501
        :type: ImdbapiPrecisionDate
        """

        self._release_date = release_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiEpisode, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiEpisode):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiEpisode):
            return True

        return self.to_dict() != other.to_dict()
