# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiMetacritic(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'url': 'str',
        'score': 'int',
        'review_count': 'int'
    }

    attribute_map = {
        'url': 'url',
        'score': 'score',
        'review_count': 'reviewCount'
    }

    def __init__(self, url=None, score=None, review_count=None, _configuration=None):  # noqa: E501
        """ImdbapiMetacritic - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._url = None
        self._score = None
        self._review_count = None
        self.discriminator = None

        if url is not None:
            self.url = url
        if score is not None:
            self.score = score
        if review_count is not None:
            self.review_count = review_count

    @property
    def url(self):
        """Gets the url of this ImdbapiMetacritic.  # noqa: E501

        Metacritic URL.  # noqa: E501

        :return: The url of this ImdbapiMetacritic.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this ImdbapiMetacritic.

        Metacritic URL.  # noqa: E501

        :param url: The url of this ImdbapiMetacritic.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def score(self):
        """Gets the score of this ImdbapiMetacritic.  # noqa: E501

        Metacritic score.  # noqa: E501

        :return: The score of this ImdbapiMetacritic.  # noqa: E501
        :rtype: int
        """
        return self._score

    @score.setter
    def score(self, score):
        """Sets the score of this ImdbapiMetacritic.

        Metacritic score.  # noqa: E501

        :param score: The score of this ImdbapiMetacritic.  # noqa: E501
        :type: int
        """

        self._score = score

    @property
    def review_count(self):
        """Gets the review_count of this ImdbapiMetacritic.  # noqa: E501

        Number of reviews.  # noqa: E501

        :return: The review_count of this ImdbapiMetacritic.  # noqa: E501
        :rtype: int
        """
        return self._review_count

    @review_count.setter
    def review_count(self, review_count):
        """Sets the review_count of this ImdbapiMetacritic.

        Number of reviews.  # noqa: E501

        :param review_count: The review_count of this ImdbapiMetacritic.  # noqa: E501
        :type: int
        """

        self._review_count = review_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiMetacritic, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiMetacritic):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiMetacritic):
            return True

        return self.to_dict() != other.to_dict()
