# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiBoxOffice(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'domestic_gross': 'ImdbapiMoney',
        'worldwide_gross': 'ImdbapiMoney',
        'opening_weekend_gross': 'ImdbapiOpeningWeekendGross',
        'production_budget': 'ImdbapiMoney'
    }

    attribute_map = {
        'domestic_gross': 'domesticGross',
        'worldwide_gross': 'worldwideGross',
        'opening_weekend_gross': 'openingWeekendGross',
        'production_budget': 'productionBudget'
    }

    def __init__(self, domestic_gross=None, worldwide_gross=None, opening_weekend_gross=None, production_budget=None, _configuration=None):  # noqa: E501
        """ImdbapiBoxOffice - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._domestic_gross = None
        self._worldwide_gross = None
        self._opening_weekend_gross = None
        self._production_budget = None
        self.discriminator = None

        if domestic_gross is not None:
            self.domestic_gross = domestic_gross
        if worldwide_gross is not None:
            self.worldwide_gross = worldwide_gross
        if opening_weekend_gross is not None:
            self.opening_weekend_gross = opening_weekend_gross
        if production_budget is not None:
            self.production_budget = production_budget

    @property
    def domestic_gross(self):
        """Gets the domestic_gross of this ImdbapiBoxOffice.  # noqa: E501

        The domestic box office gross for the movie.  # noqa: E501

        :return: The domestic_gross of this ImdbapiBoxOffice.  # noqa: E501
        :rtype: ImdbapiMoney
        """
        return self._domestic_gross

    @domestic_gross.setter
    def domestic_gross(self, domestic_gross):
        """Sets the domestic_gross of this ImdbapiBoxOffice.

        The domestic box office gross for the movie.  # noqa: E501

        :param domestic_gross: The domestic_gross of this ImdbapiBoxOffice.  # noqa: E501
        :type: ImdbapiMoney
        """

        self._domestic_gross = domestic_gross

    @property
    def worldwide_gross(self):
        """Gets the worldwide_gross of this ImdbapiBoxOffice.  # noqa: E501

        The total worldwide box office gross for the movie.  # noqa: E501

        :return: The worldwide_gross of this ImdbapiBoxOffice.  # noqa: E501
        :rtype: ImdbapiMoney
        """
        return self._worldwide_gross

    @worldwide_gross.setter
    def worldwide_gross(self, worldwide_gross):
        """Sets the worldwide_gross of this ImdbapiBoxOffice.

        The total worldwide box office gross for the movie.  # noqa: E501

        :param worldwide_gross: The worldwide_gross of this ImdbapiBoxOffice.  # noqa: E501
        :type: ImdbapiMoney
        """

        self._worldwide_gross = worldwide_gross

    @property
    def opening_weekend_gross(self):
        """Gets the opening_weekend_gross of this ImdbapiBoxOffice.  # noqa: E501

        The opening weekend box office gross for the movie.  # noqa: E501

        :return: The opening_weekend_gross of this ImdbapiBoxOffice.  # noqa: E501
        :rtype: ImdbapiOpeningWeekendGross
        """
        return self._opening_weekend_gross

    @opening_weekend_gross.setter
    def opening_weekend_gross(self, opening_weekend_gross):
        """Sets the opening_weekend_gross of this ImdbapiBoxOffice.

        The opening weekend box office gross for the movie.  # noqa: E501

        :param opening_weekend_gross: The opening_weekend_gross of this ImdbapiBoxOffice.  # noqa: E501
        :type: ImdbapiOpeningWeekendGross
        """

        self._opening_weekend_gross = opening_weekend_gross

    @property
    def production_budget(self):
        """Gets the production_budget of this ImdbapiBoxOffice.  # noqa: E501

        The production budget for the movie.  # noqa: E501

        :return: The production_budget of this ImdbapiBoxOffice.  # noqa: E501
        :rtype: ImdbapiMoney
        """
        return self._production_budget

    @production_budget.setter
    def production_budget(self, production_budget):
        """Sets the production_budget of this ImdbapiBoxOffice.

        The production budget for the movie.  # noqa: E501

        :param production_budget: The production_budget of this ImdbapiBoxOffice.  # noqa: E501
        :type: ImdbapiMoney
        """

        self._production_budget = production_budget

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiBoxOffice, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiBoxOffice):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiBoxOffice):
            return True

        return self.to_dict() != other.to_dict()
