# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiListTitleSeasonsResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'seasons': 'list[ImdbapiSeason]'
    }

    attribute_map = {
        'seasons': 'seasons'
    }

    def __init__(self, seasons=None, _configuration=None):  # noqa: E501
        """ImdbapiListTitleSeasonsResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._seasons = None
        self.discriminator = None

        if seasons is not None:
            self.seasons = seasons

    @property
    def seasons(self):
        """Gets the seasons of this ImdbapiListTitleSeasonsResponse.  # noqa: E501

        List of seasons associated with the title.  # noqa: E501

        :return: The seasons of this ImdbapiListTitleSeasonsResponse.  # noqa: E501
        :rtype: list[ImdbapiSeason]
        """
        return self._seasons

    @seasons.setter
    def seasons(self, seasons):
        """Sets the seasons of this ImdbapiListTitleSeasonsResponse.

        List of seasons associated with the title.  # noqa: E501

        :param seasons: The seasons of this ImdbapiListTitleSeasonsResponse.  # noqa: E501
        :type: list[ImdbapiSeason]
        """

        self._seasons = seasons

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiListTitleSeasonsResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiListTitleSeasonsResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiListTitleSeasonsResponse):
            return True

        return self.to_dict() != other.to_dict()
