# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiAKA(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'text': 'str',
        'country': 'ImdbapiCountry',
        'language': 'ImdbapiLanguage',
        'attributes': 'list[str]'
    }

    attribute_map = {
        'text': 'text',
        'country': 'country',
        'language': 'language',
        'attributes': 'attributes'
    }

    def __init__(self, text=None, country=None, language=None, attributes=None, _configuration=None):  # noqa: E501
        """ImdbapiAKA - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._text = None
        self._country = None
        self._language = None
        self._attributes = None
        self.discriminator = None

        if text is not None:
            self.text = text
        if country is not None:
            self.country = country
        if language is not None:
            self.language = language
        if attributes is not None:
            self.attributes = attributes

    @property
    def text(self):
        """Gets the text of this ImdbapiAKA.  # noqa: E501

        The display text of the title in the specified language and country.  # noqa: E501

        :return: The text of this ImdbapiAKA.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this ImdbapiAKA.

        The display text of the title in the specified language and country.  # noqa: E501

        :param text: The text of this ImdbapiAKA.  # noqa: E501
        :type: str
        """

        self._text = text

    @property
    def country(self):
        """Gets the country of this ImdbapiAKA.  # noqa: E501

        The country where this title is used, represented by its ISO 3166-1 alpha-2 code.  # noqa: E501

        :return: The country of this ImdbapiAKA.  # noqa: E501
        :rtype: ImdbapiCountry
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this ImdbapiAKA.

        The country where this title is used, represented by its ISO 3166-1 alpha-2 code.  # noqa: E501

        :param country: The country of this ImdbapiAKA.  # noqa: E501
        :type: ImdbapiCountry
        """

        self._country = country

    @property
    def language(self):
        """Gets the language of this ImdbapiAKA.  # noqa: E501

        The language of the title, represented by its ISO 639-3 code.  # noqa: E501

        :return: The language of this ImdbapiAKA.  # noqa: E501
        :rtype: ImdbapiLanguage
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this ImdbapiAKA.

        The language of the title, represented by its ISO 639-3 code.  # noqa: E501

        :param language: The language of this ImdbapiAKA.  # noqa: E501
        :type: ImdbapiLanguage
        """

        self._language = language

    @property
    def attributes(self):
        """Gets the attributes of this ImdbapiAKA.  # noqa: E501

        Additional attributes related to the title, such as \"original title\", \"working title\", or \"alternative title\".  # noqa: E501

        :return: The attributes of this ImdbapiAKA.  # noqa: E501
        :rtype: list[str]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this ImdbapiAKA.

        Additional attributes related to the title, such as \"original title\", \"working title\", or \"alternative title\".  # noqa: E501

        :param attributes: The attributes of this ImdbapiAKA.  # noqa: E501
        :type: list[str]
        """

        self._attributes = attributes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiAKA, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiAKA):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiAKA):
            return True

        return self.to_dict() != other.to_dict()
