# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiParentsGuideReview(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'text': 'str',
        'is_spoiler': 'bool'
    }

    attribute_map = {
        'text': 'text',
        'is_spoiler': 'isSpoiler'
    }

    def __init__(self, text=None, is_spoiler=None, _configuration=None):  # noqa: E501
        """ImdbapiParentsGuideReview - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._text = None
        self._is_spoiler = None
        self.discriminator = None

        if text is not None:
            self.text = text
        if is_spoiler is not None:
            self.is_spoiler = is_spoiler

    @property
    def text(self):
        """Gets the text of this ImdbapiParentsGuideReview.  # noqa: E501


        :return: The text of this ImdbapiParentsGuideReview.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this ImdbapiParentsGuideReview.


        :param text: The text of this ImdbapiParentsGuideReview.  # noqa: E501
        :type: str
        """

        self._text = text

    @property
    def is_spoiler(self):
        """Gets the is_spoiler of this ImdbapiParentsGuideReview.  # noqa: E501


        :return: The is_spoiler of this ImdbapiParentsGuideReview.  # noqa: E501
        :rtype: bool
        """
        return self._is_spoiler

    @is_spoiler.setter
    def is_spoiler(self, is_spoiler):
        """Sets the is_spoiler of this ImdbapiParentsGuideReview.


        :param is_spoiler: The is_spoiler of this ImdbapiParentsGuideReview.  # noqa: E501
        :type: bool
        """

        self._is_spoiler = is_spoiler

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiParentsGuideReview, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiParentsGuideReview):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiParentsGuideReview):
            return True

        return self.to_dict() != other.to_dict()
