# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from py_imdb_api_dev_client.configuration import Configuration


class ImdbapiTitle(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'type': 'str',
        'is_adult': 'bool',
        'primary_title': 'str',
        'original_title': 'str',
        'primary_image': 'ImdbapiImage',
        'start_year': 'int',
        'end_year': 'int',
        'runtime_seconds': 'int',
        'genres': 'list[str]',
        'rating': 'ImdbapiRating',
        'metacritic': 'ImdbapiMetacritic',
        'plot': 'str',
        'directors': 'list[ImdbapiName]',
        'writers': 'list[ImdbapiName]',
        'stars': 'list[ImdbapiName]',
        'origin_countries': 'list[ImdbapiCountry]',
        'spoken_languages': 'list[ImdbapiLanguage]',
        'interests': 'list[ImdbapiInterest]'
    }

    attribute_map = {
        'id': 'id',
        'type': 'type',
        'is_adult': 'isAdult',
        'primary_title': 'primaryTitle',
        'original_title': 'originalTitle',
        'primary_image': 'primaryImage',
        'start_year': 'startYear',
        'end_year': 'endYear',
        'runtime_seconds': 'runtimeSeconds',
        'genres': 'genres',
        'rating': 'rating',
        'metacritic': 'metacritic',
        'plot': 'plot',
        'directors': 'directors',
        'writers': 'writers',
        'stars': 'stars',
        'origin_countries': 'originCountries',
        'spoken_languages': 'spokenLanguages',
        'interests': 'interests'
    }

    def __init__(self, id=None, type=None, is_adult=None, primary_title=None, original_title=None, primary_image=None, start_year=None, end_year=None, runtime_seconds=None, genres=None, rating=None, metacritic=None, plot=None, directors=None, writers=None, stars=None, origin_countries=None, spoken_languages=None, interests=None, _configuration=None):  # noqa: E501
        """ImdbapiTitle - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._type = None
        self._is_adult = None
        self._primary_title = None
        self._original_title = None
        self._primary_image = None
        self._start_year = None
        self._end_year = None
        self._runtime_seconds = None
        self._genres = None
        self._rating = None
        self._metacritic = None
        self._plot = None
        self._directors = None
        self._writers = None
        self._stars = None
        self._origin_countries = None
        self._spoken_languages = None
        self._interests = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if type is not None:
            self.type = type
        if is_adult is not None:
            self.is_adult = is_adult
        if primary_title is not None:
            self.primary_title = primary_title
        if original_title is not None:
            self.original_title = original_title
        if primary_image is not None:
            self.primary_image = primary_image
        if start_year is not None:
            self.start_year = start_year
        if end_year is not None:
            self.end_year = end_year
        if runtime_seconds is not None:
            self.runtime_seconds = runtime_seconds
        if genres is not None:
            self.genres = genres
        if rating is not None:
            self.rating = rating
        if metacritic is not None:
            self.metacritic = metacritic
        if plot is not None:
            self.plot = plot
        if directors is not None:
            self.directors = directors
        if writers is not None:
            self.writers = writers
        if stars is not None:
            self.stars = stars
        if origin_countries is not None:
            self.origin_countries = origin_countries
        if spoken_languages is not None:
            self.spoken_languages = spoken_languages
        if interests is not None:
            self.interests = interests

    @property
    def id(self):
        """Gets the id of this ImdbapiTitle.  # noqa: E501

        The unique identifier for the title.  # noqa: E501

        :return: The id of this ImdbapiTitle.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ImdbapiTitle.

        The unique identifier for the title.  # noqa: E501

        :param id: The id of this ImdbapiTitle.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def type(self):
        """Gets the type of this ImdbapiTitle.  # noqa: E501

        The type of the title, such as \"movie\", \"tvSeries\", \"tvEpisode\", etc.  # noqa: E501

        :return: The type of this ImdbapiTitle.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ImdbapiTitle.

        The type of the title, such as \"movie\", \"tvSeries\", \"tvEpisode\", etc.  # noqa: E501

        :param type: The type of this ImdbapiTitle.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def is_adult(self):
        """Gets the is_adult of this ImdbapiTitle.  # noqa: E501

        The is_adult field indicates whether the title is intended for adult audiences.  # noqa: E501

        :return: The is_adult of this ImdbapiTitle.  # noqa: E501
        :rtype: bool
        """
        return self._is_adult

    @is_adult.setter
    def is_adult(self, is_adult):
        """Sets the is_adult of this ImdbapiTitle.

        The is_adult field indicates whether the title is intended for adult audiences.  # noqa: E501

        :param is_adult: The is_adult of this ImdbapiTitle.  # noqa: E501
        :type: bool
        """

        self._is_adult = is_adult

    @property
    def primary_title(self):
        """Gets the primary_title of this ImdbapiTitle.  # noqa: E501

        The primary title of the title, which is typically the most recognized name.  # noqa: E501

        :return: The primary_title of this ImdbapiTitle.  # noqa: E501
        :rtype: str
        """
        return self._primary_title

    @primary_title.setter
    def primary_title(self, primary_title):
        """Sets the primary_title of this ImdbapiTitle.

        The primary title of the title, which is typically the most recognized name.  # noqa: E501

        :param primary_title: The primary_title of this ImdbapiTitle.  # noqa: E501
        :type: str
        """

        self._primary_title = primary_title

    @property
    def original_title(self):
        """Gets the original_title of this ImdbapiTitle.  # noqa: E501

        The original title of the title, normally which is the title as it was originally released.  # noqa: E501

        :return: The original_title of this ImdbapiTitle.  # noqa: E501
        :rtype: str
        """
        return self._original_title

    @original_title.setter
    def original_title(self, original_title):
        """Sets the original_title of this ImdbapiTitle.

        The original title of the title, normally which is the title as it was originally released.  # noqa: E501

        :param original_title: The original_title of this ImdbapiTitle.  # noqa: E501
        :type: str
        """

        self._original_title = original_title

    @property
    def primary_image(self):
        """Gets the primary_image of this ImdbapiTitle.  # noqa: E501

        The primary image associated with the title, such as a poster.  # noqa: E501

        :return: The primary_image of this ImdbapiTitle.  # noqa: E501
        :rtype: ImdbapiImage
        """
        return self._primary_image

    @primary_image.setter
    def primary_image(self, primary_image):
        """Sets the primary_image of this ImdbapiTitle.

        The primary image associated with the title, such as a poster.  # noqa: E501

        :param primary_image: The primary_image of this ImdbapiTitle.  # noqa: E501
        :type: ImdbapiImage
        """

        self._primary_image = primary_image

    @property
    def start_year(self):
        """Gets the start_year of this ImdbapiTitle.  # noqa: E501

        The start_year field is used for titles that have a defined start, such as movies or TV series.  # noqa: E501

        :return: The start_year of this ImdbapiTitle.  # noqa: E501
        :rtype: int
        """
        return self._start_year

    @start_year.setter
    def start_year(self, start_year):
        """Sets the start_year of this ImdbapiTitle.

        The start_year field is used for titles that have a defined start, such as movies or TV series.  # noqa: E501

        :param start_year: The start_year of this ImdbapiTitle.  # noqa: E501
        :type: int
        """

        self._start_year = start_year

    @property
    def end_year(self):
        """Gets the end_year of this ImdbapiTitle.  # noqa: E501

        The end_year field is used for titles that have a defined end, such as TV series.  # noqa: E501

        :return: The end_year of this ImdbapiTitle.  # noqa: E501
        :rtype: int
        """
        return self._end_year

    @end_year.setter
    def end_year(self, end_year):
        """Sets the end_year of this ImdbapiTitle.

        The end_year field is used for titles that have a defined end, such as TV series.  # noqa: E501

        :param end_year: The end_year of this ImdbapiTitle.  # noqa: E501
        :type: int
        """

        self._end_year = end_year

    @property
    def runtime_seconds(self):
        """Gets the runtime_seconds of this ImdbapiTitle.  # noqa: E501

        The runtime_seconds field contains the total runtime of the title in minutes.  # noqa: E501

        :return: The runtime_seconds of this ImdbapiTitle.  # noqa: E501
        :rtype: int
        """
        return self._runtime_seconds

    @runtime_seconds.setter
    def runtime_seconds(self, runtime_seconds):
        """Sets the runtime_seconds of this ImdbapiTitle.

        The runtime_seconds field contains the total runtime of the title in minutes.  # noqa: E501

        :param runtime_seconds: The runtime_seconds of this ImdbapiTitle.  # noqa: E501
        :type: int
        """

        self._runtime_seconds = runtime_seconds

    @property
    def genres(self):
        """Gets the genres of this ImdbapiTitle.  # noqa: E501

        The genres field contains a list of genres associated with the title.  # noqa: E501

        :return: The genres of this ImdbapiTitle.  # noqa: E501
        :rtype: list[str]
        """
        return self._genres

    @genres.setter
    def genres(self, genres):
        """Sets the genres of this ImdbapiTitle.

        The genres field contains a list of genres associated with the title.  # noqa: E501

        :param genres: The genres of this ImdbapiTitle.  # noqa: E501
        :type: list[str]
        """

        self._genres = genres

    @property
    def rating(self):
        """Gets the rating of this ImdbapiTitle.  # noqa: E501

        The rating field contains the aggregate rating and the number of votes for the title.  # noqa: E501

        :return: The rating of this ImdbapiTitle.  # noqa: E501
        :rtype: ImdbapiRating
        """
        return self._rating

    @rating.setter
    def rating(self, rating):
        """Sets the rating of this ImdbapiTitle.

        The rating field contains the aggregate rating and the number of votes for the title.  # noqa: E501

        :param rating: The rating of this ImdbapiTitle.  # noqa: E501
        :type: ImdbapiRating
        """

        self._rating = rating

    @property
    def metacritic(self):
        """Gets the metacritic of this ImdbapiTitle.  # noqa: E501

        The metacritic information for the title, such as score and reviews.  # noqa: E501

        :return: The metacritic of this ImdbapiTitle.  # noqa: E501
        :rtype: ImdbapiMetacritic
        """
        return self._metacritic

    @metacritic.setter
    def metacritic(self, metacritic):
        """Sets the metacritic of this ImdbapiTitle.

        The metacritic information for the title, such as score and reviews.  # noqa: E501

        :param metacritic: The metacritic of this ImdbapiTitle.  # noqa: E501
        :type: ImdbapiMetacritic
        """

        self._metacritic = metacritic

    @property
    def plot(self):
        """Gets the plot of this ImdbapiTitle.  # noqa: E501

        The plot field contains a brief summary or description of the title's storyline.  # noqa: E501

        :return: The plot of this ImdbapiTitle.  # noqa: E501
        :rtype: str
        """
        return self._plot

    @plot.setter
    def plot(self, plot):
        """Sets the plot of this ImdbapiTitle.

        The plot field contains a brief summary or description of the title's storyline.  # noqa: E501

        :param plot: The plot of this ImdbapiTitle.  # noqa: E501
        :type: str
        """

        self._plot = plot

    @property
    def directors(self):
        """Gets the directors of this ImdbapiTitle.  # noqa: E501

        The list of directors associated with the title, which can include multiple directors.  # noqa: E501

        :return: The directors of this ImdbapiTitle.  # noqa: E501
        :rtype: list[ImdbapiName]
        """
        return self._directors

    @directors.setter
    def directors(self, directors):
        """Sets the directors of this ImdbapiTitle.

        The list of directors associated with the title, which can include multiple directors.  # noqa: E501

        :param directors: The directors of this ImdbapiTitle.  # noqa: E501
        :type: list[ImdbapiName]
        """

        self._directors = directors

    @property
    def writers(self):
        """Gets the writers of this ImdbapiTitle.  # noqa: E501

        The list of writers associated with the title, which can include multiple writers.  # noqa: E501

        :return: The writers of this ImdbapiTitle.  # noqa: E501
        :rtype: list[ImdbapiName]
        """
        return self._writers

    @writers.setter
    def writers(self, writers):
        """Sets the writers of this ImdbapiTitle.

        The list of writers associated with the title, which can include multiple writers.  # noqa: E501

        :param writers: The writers of this ImdbapiTitle.  # noqa: E501
        :type: list[ImdbapiName]
        """

        self._writers = writers

    @property
    def stars(self):
        """Gets the stars of this ImdbapiTitle.  # noqa: E501

        The list of stars associated with the title, which can include multiple actors or actresses.  # noqa: E501

        :return: The stars of this ImdbapiTitle.  # noqa: E501
        :rtype: list[ImdbapiName]
        """
        return self._stars

    @stars.setter
    def stars(self, stars):
        """Sets the stars of this ImdbapiTitle.

        The list of stars associated with the title, which can include multiple actors or actresses.  # noqa: E501

        :param stars: The stars of this ImdbapiTitle.  # noqa: E501
        :type: list[ImdbapiName]
        """

        self._stars = stars

    @property
    def origin_countries(self):
        """Gets the origin_countries of this ImdbapiTitle.  # noqa: E501

        The list of countries where the title was produced or is associated with.  # noqa: E501

        :return: The origin_countries of this ImdbapiTitle.  # noqa: E501
        :rtype: list[ImdbapiCountry]
        """
        return self._origin_countries

    @origin_countries.setter
    def origin_countries(self, origin_countries):
        """Sets the origin_countries of this ImdbapiTitle.

        The list of countries where the title was produced or is associated with.  # noqa: E501

        :param origin_countries: The origin_countries of this ImdbapiTitle.  # noqa: E501
        :type: list[ImdbapiCountry]
        """

        self._origin_countries = origin_countries

    @property
    def spoken_languages(self):
        """Gets the spoken_languages of this ImdbapiTitle.  # noqa: E501

        The list of languages spoken in the title, which can include multiple languages.  # noqa: E501

        :return: The spoken_languages of this ImdbapiTitle.  # noqa: E501
        :rtype: list[ImdbapiLanguage]
        """
        return self._spoken_languages

    @spoken_languages.setter
    def spoken_languages(self, spoken_languages):
        """Sets the spoken_languages of this ImdbapiTitle.

        The list of languages spoken in the title, which can include multiple languages.  # noqa: E501

        :param spoken_languages: The spoken_languages of this ImdbapiTitle.  # noqa: E501
        :type: list[ImdbapiLanguage]
        """

        self._spoken_languages = spoken_languages

    @property
    def interests(self):
        """Gets the interests of this ImdbapiTitle.  # noqa: E501

        The list of interests associated with the title.  # noqa: E501

        :return: The interests of this ImdbapiTitle.  # noqa: E501
        :rtype: list[ImdbapiInterest]
        """
        return self._interests

    @interests.setter
    def interests(self, interests):
        """Sets the interests of this ImdbapiTitle.

        The list of interests associated with the title.  # noqa: E501

        :param interests: The interests of this ImdbapiTitle.  # noqa: E501
        :type: list[ImdbapiInterest]
        """

        self._interests = interests

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImdbapiTitle, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImdbapiTitle):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImdbapiTitle):
            return True

        return self.to_dict() != other.to_dict()
