# coding: utf-8

"""
    IMDbAPI

    This is beta version of the IMDb API. It is not yet stable and may change in the future.  # noqa: E501

    OpenAPI spec version: 2.0.2-beta
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import py_imdb_api_dev_client
from py_imdb_api_dev_client.models.protobuf_any import ProtobufAny  # noqa: E501
from py_imdb_api_dev_client.rest import ApiException


class TestProtobufAny(unittest.TestCase):
    """ProtobufAny unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProtobufAny(self):
        """Test ProtobufAny"""
        # FIXME: construct object with mandatory attributes with example values
        # model = py_imdb_api_dev_client.models.protobuf_any.ProtobufAny()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
