# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import py_imdb_api_dev_client
from py_imdb_api_dev_client.models.imdbapi_list_list_interest_categories_response import ImdbapiListListInterestCategoriesResponse  # noqa: E501
from py_imdb_api_dev_client.rest import ApiException


class TestImdbapiListListInterestCategoriesResponse(unittest.TestCase):
    """ImdbapiListListInterestCategoriesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImdbapiListListInterestCategoriesResponse(self):
        """Test ImdbapiListListInterestCategoriesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = py_imdb_api_dev_client.models.imdbapi_list_list_interest_categories_response.ImdbapiListListInterestCategoriesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
