# coding: utf-8

"""
    IMDbAPI

    This is beta version of the IMDb API. It is not yet stable and may change in the future.  # noqa: E501

    OpenAPI spec version: 2.0.2-beta
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import py_imdb_api_dev_client
from imdbapi.name_api import NameApi  # noqa: E501
from py_imdb_api_dev_client.rest import ApiException


class TestNameApi(unittest.TestCase):
    """NameApi unit test stubs"""

    def setUp(self):
        self.api = imdbapi.name_api.NameApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_i_mdb_api_service_batch_get_names(self):
        """Test case for i_mdb_api_service_batch_get_names

        Batch get names by IDs  # noqa: E501
        """
        pass

    def test_i_mdb_api_service_get_name(self):
        """Test case for i_mdb_api_service_get_name

        Get name by ID  # noqa: E501
        """
        pass

    def test_i_mdb_api_service_list_name_known_for(self):
        """Test case for i_mdb_api_service_list_name_known_for

        List known for credits for a name  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
