# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import py_imdb_api_dev_client
from imdbapi.interest_api import InterestApi  # noqa: E501
from py_imdb_api_dev_client.rest import ApiException


class TestInterestApi(unittest.TestCase):
    """InterestApi unit test stubs"""

    def setUp(self):
        self.api = imdbapi.interest_api.InterestApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_i_mdb_api_service_get_interest(self):
        """Test case for i_mdb_api_service_get_interest

        Get interest by ID  # noqa: E501
        """
        pass

    def test_i_mdb_api_service_list_interest_categories(self):
        """Test case for i_mdb_api_service_list_interest_categories

        List interest categories  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
