# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import py_imdb_api_dev_client
from py_imdb_api_dev_client.models.imdbapi_award_nomination_stats import ImdbapiAwardNominationStats  # noqa: E501
from py_imdb_api_dev_client.rest import ApiException


class TestImdbapiAwardNominationStats(unittest.TestCase):
    """ImdbapiAwardNominationStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImdbapiAwardNominationStats(self):
        """Test ImdbapiAwardNominationStats"""
        # FIXME: construct object with mandatory attributes with example values
        # model = py_imdb_api_dev_client.models.imdbapi_award_nomination_stats.ImdbapiAwardNominationStats()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
