# coding: utf-8

"""
    IMDbAPI

    This is beta version of the IMDb API. It is not yet stable and may change in the future.  # noqa: E501

    OpenAPI spec version: 2.0.2-beta
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import py_imdb_api_dev_client
from imdbapi.title_api import TitleApi  # noqa: E501
from py_imdb_api_dev_client.rest import ApiException


class TestTitleApi(unittest.TestCase):
    """TitleApi unit test stubs"""

    def setUp(self):
        self.api = imdbapi.title_api.TitleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_i_mdb_api_service_batch_get_titles(self):
        """Test case for i_mdb_api_service_batch_get_titles

        Batch get titles by IDs  # noqa: E501
        """
        pass

    def test_i_mdb_api_service_get_title(self):
        """Test case for i_mdb_api_service_get_title

        Get title by ID  # noqa: E501
        """
        pass

    def test_i_mdb_api_service_list_title_akas(self):
        """Test case for i_mdb_api_service_list_title_akas

        List AKAs for a title  # noqa: E501
        """
        pass

    def test_i_mdb_api_service_list_title_credits(self):
        """Test case for i_mdb_api_service_list_title_credits

        List credits for a title  # noqa: E501
        """
        pass

    def test_i_mdb_api_service_list_title_release_dates(self):
        """Test case for i_mdb_api_service_list_title_release_dates

        List release dates for a title  # noqa: E501
        """
        pass

    def test_i_mdb_api_service_search_titles(self):
        """Test case for i_mdb_api_service_search_titles

        Search titles by query  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
