# coding: utf-8

"""
    IMDbAPI

    IMDb API for accessing movie and TV show data  # noqa: E501

    OpenAPI spec version: 2.7.12
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from py_imdb_api_dev_client.api_client import ApiClient


class TitleApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def i_mdb_api_service_batch_get_titles(self, title_ids, **kwargs):  # noqa: E501
        """Batch get titles by IDs  # noqa: E501

        Retrieve details of multiple titles using their IMDb IDs.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_batch_get_titles(title_ids, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] title_ids: List of IMDb title IDs. Maximum 5 IDs. (required)
        :return: ImdbapiBatchGetTitlesResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.i_mdb_api_service_batch_get_titles_with_http_info(title_ids, **kwargs)  # noqa: E501
        else:
            (data) = self.i_mdb_api_service_batch_get_titles_with_http_info(title_ids, **kwargs)  # noqa: E501
            return data

    def i_mdb_api_service_batch_get_titles_with_http_info(self, title_ids, **kwargs):  # noqa: E501
        """Batch get titles by IDs  # noqa: E501

        Retrieve details of multiple titles using their IMDb IDs.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_batch_get_titles_with_http_info(title_ids, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] title_ids: List of IMDb title IDs. Maximum 5 IDs. (required)
        :return: ImdbapiBatchGetTitlesResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['title_ids']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method i_mdb_api_service_batch_get_titles" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'title_ids' is set
        if self.api_client.client_side_validation and ('title_ids' not in params or
                                                       params['title_ids'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `title_ids` when calling `i_mdb_api_service_batch_get_titles`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'title_ids' in params:
            query_params.append(('titleIds', params['title_ids']))  # noqa: E501
            collection_formats['titleIds'] = 'multi'  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/titles:batchGet', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ImdbapiBatchGetTitlesResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def i_mdb_api_service_get_title(self, title_id, **kwargs):  # noqa: E501
        """Get title by ID  # noqa: E501

        Retrieve a title's details using its IMDb ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_get_title(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: The IMDb title ID in the format 'tt1234567'. (required)
        :return: ImdbapiTitle
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.i_mdb_api_service_get_title_with_http_info(title_id, **kwargs)  # noqa: E501
        else:
            (data) = self.i_mdb_api_service_get_title_with_http_info(title_id, **kwargs)  # noqa: E501
            return data

    def i_mdb_api_service_get_title_with_http_info(self, title_id, **kwargs):  # noqa: E501
        """Get title by ID  # noqa: E501

        Retrieve a title's details using its IMDb ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_get_title_with_http_info(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: The IMDb title ID in the format 'tt1234567'. (required)
        :return: ImdbapiTitle
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['title_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method i_mdb_api_service_get_title" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'title_id' is set
        if self.api_client.client_side_validation and ('title_id' not in params or
                                                       params['title_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `title_id` when calling `i_mdb_api_service_get_title`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'title_id' in params:
            path_params['titleId'] = params['title_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/titles/{titleId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ImdbapiTitle',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def i_mdb_api_service_get_title_box_office(self, title_id, **kwargs):  # noqa: E501
        """Get box office information for a title  # noqa: E501

        Retrieve the box office information associated with a specific title.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_get_title_box_office(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: Required. IMDb title ID in the format \"tt1234567\". (required)
        :return: ImdbapiBoxOffice
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.i_mdb_api_service_get_title_box_office_with_http_info(title_id, **kwargs)  # noqa: E501
        else:
            (data) = self.i_mdb_api_service_get_title_box_office_with_http_info(title_id, **kwargs)  # noqa: E501
            return data

    def i_mdb_api_service_get_title_box_office_with_http_info(self, title_id, **kwargs):  # noqa: E501
        """Get box office information for a title  # noqa: E501

        Retrieve the box office information associated with a specific title.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_get_title_box_office_with_http_info(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: Required. IMDb title ID in the format \"tt1234567\". (required)
        :return: ImdbapiBoxOffice
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['title_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method i_mdb_api_service_get_title_box_office" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'title_id' is set
        if self.api_client.client_side_validation and ('title_id' not in params or
                                                       params['title_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `title_id` when calling `i_mdb_api_service_get_title_box_office`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'title_id' in params:
            path_params['titleId'] = params['title_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/titles/{titleId}/boxOffice', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ImdbapiBoxOffice',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def i_mdb_api_service_list_title_akas(self, title_id, **kwargs):  # noqa: E501
        """List AKAs for a title  # noqa: E501

        Retrieve the alternative titles (AKAs) associated with a specific title.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_list_title_akas(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: Required. IMDb title ID in the format \"tt1234567\". (required)
        :return: ImdbapiListTitleAKAsResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.i_mdb_api_service_list_title_akas_with_http_info(title_id, **kwargs)  # noqa: E501
        else:
            (data) = self.i_mdb_api_service_list_title_akas_with_http_info(title_id, **kwargs)  # noqa: E501
            return data

    def i_mdb_api_service_list_title_akas_with_http_info(self, title_id, **kwargs):  # noqa: E501
        """List AKAs for a title  # noqa: E501

        Retrieve the alternative titles (AKAs) associated with a specific title.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_list_title_akas_with_http_info(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: Required. IMDb title ID in the format \"tt1234567\". (required)
        :return: ImdbapiListTitleAKAsResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['title_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method i_mdb_api_service_list_title_akas" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'title_id' is set
        if self.api_client.client_side_validation and ('title_id' not in params or
                                                       params['title_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `title_id` when calling `i_mdb_api_service_list_title_akas`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'title_id' in params:
            path_params['titleId'] = params['title_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/titles/{titleId}/akas', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ImdbapiListTitleAKAsResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def i_mdb_api_service_list_title_award_nominations(self, title_id, **kwargs):  # noqa: E501
        """List award nominations for a title  # noqa: E501

        Retrieve the award nominations associated with a specific title.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_list_title_award_nominations(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: Required. IMDb title ID in the format \"tt1234567\". (required)
        :param int page_size: Optional. The maximum number of award nominations to return per page. If not specified, a default value will be used.  The value must be between 1 and 50. Default is 20.
        :param str page_token: Optional. Token for pagination, if applicable.
        :return: ImdbapiListTitleAwardNominationsResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.i_mdb_api_service_list_title_award_nominations_with_http_info(title_id, **kwargs)  # noqa: E501
        else:
            (data) = self.i_mdb_api_service_list_title_award_nominations_with_http_info(title_id, **kwargs)  # noqa: E501
            return data

    def i_mdb_api_service_list_title_award_nominations_with_http_info(self, title_id, **kwargs):  # noqa: E501
        """List award nominations for a title  # noqa: E501

        Retrieve the award nominations associated with a specific title.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_list_title_award_nominations_with_http_info(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: Required. IMDb title ID in the format \"tt1234567\". (required)
        :param int page_size: Optional. The maximum number of award nominations to return per page. If not specified, a default value will be used.  The value must be between 1 and 50. Default is 20.
        :param str page_token: Optional. Token for pagination, if applicable.
        :return: ImdbapiListTitleAwardNominationsResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['title_id', 'page_size', 'page_token']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method i_mdb_api_service_list_title_award_nominations" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'title_id' is set
        if self.api_client.client_side_validation and ('title_id' not in params or
                                                       params['title_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `title_id` when calling `i_mdb_api_service_list_title_award_nominations`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'title_id' in params:
            path_params['titleId'] = params['title_id']  # noqa: E501

        query_params = []
        if 'page_size' in params:
            query_params.append(('pageSize', params['page_size']))  # noqa: E501
        if 'page_token' in params:
            query_params.append(('pageToken', params['page_token']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/titles/{titleId}/awardNominations', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ImdbapiListTitleAwardNominationsResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def i_mdb_api_service_list_title_certificates(self, title_id, **kwargs):  # noqa: E501
        """List certificates for a title  # noqa: E501

        Retrieve the certificates associated with a specific title.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_list_title_certificates(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: Required. IMDb title ID in the format \"tt1234567\". (required)
        :return: ImdbapiListTitleCertificatesResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.i_mdb_api_service_list_title_certificates_with_http_info(title_id, **kwargs)  # noqa: E501
        else:
            (data) = self.i_mdb_api_service_list_title_certificates_with_http_info(title_id, **kwargs)  # noqa: E501
            return data

    def i_mdb_api_service_list_title_certificates_with_http_info(self, title_id, **kwargs):  # noqa: E501
        """List certificates for a title  # noqa: E501

        Retrieve the certificates associated with a specific title.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_list_title_certificates_with_http_info(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: Required. IMDb title ID in the format \"tt1234567\". (required)
        :return: ImdbapiListTitleCertificatesResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['title_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method i_mdb_api_service_list_title_certificates" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'title_id' is set
        if self.api_client.client_side_validation and ('title_id' not in params or
                                                       params['title_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `title_id` when calling `i_mdb_api_service_list_title_certificates`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'title_id' in params:
            path_params['titleId'] = params['title_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/titles/{titleId}/certificates', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ImdbapiListTitleCertificatesResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def i_mdb_api_service_list_title_company_credits(self, title_id, **kwargs):  # noqa: E501
        """List company credits for a title  # noqa: E501

        Retrieve the company credits associated with a specific title.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_list_title_company_credits(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: Required. IMDb title ID in the format \"tt1234567\". (required)
        :param list[str] categories: Optional. The categories of company credits to filter by.
        :param int page_size: Optional. The maximum number of company credits to return per page. If not specified, a default value will be used.  The value must be between 1 and 50. Default is 20.
        :param str page_token: Optional. Token for pagination, if applicable.
        :return: ImdbapiListTitleCompanyCreditsResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.i_mdb_api_service_list_title_company_credits_with_http_info(title_id, **kwargs)  # noqa: E501
        else:
            (data) = self.i_mdb_api_service_list_title_company_credits_with_http_info(title_id, **kwargs)  # noqa: E501
            return data

    def i_mdb_api_service_list_title_company_credits_with_http_info(self, title_id, **kwargs):  # noqa: E501
        """List company credits for a title  # noqa: E501

        Retrieve the company credits associated with a specific title.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_list_title_company_credits_with_http_info(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: Required. IMDb title ID in the format \"tt1234567\". (required)
        :param list[str] categories: Optional. The categories of company credits to filter by.
        :param int page_size: Optional. The maximum number of company credits to return per page. If not specified, a default value will be used.  The value must be between 1 and 50. Default is 20.
        :param str page_token: Optional. Token for pagination, if applicable.
        :return: ImdbapiListTitleCompanyCreditsResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['title_id', 'categories', 'page_size', 'page_token']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method i_mdb_api_service_list_title_company_credits" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'title_id' is set
        if self.api_client.client_side_validation and ('title_id' not in params or
                                                       params['title_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `title_id` when calling `i_mdb_api_service_list_title_company_credits`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'title_id' in params:
            path_params['titleId'] = params['title_id']  # noqa: E501

        query_params = []
        if 'categories' in params:
            query_params.append(('categories', params['categories']))  # noqa: E501
            collection_formats['categories'] = 'multi'  # noqa: E501
        if 'page_size' in params:
            query_params.append(('pageSize', params['page_size']))  # noqa: E501
        if 'page_token' in params:
            query_params.append(('pageToken', params['page_token']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/titles/{titleId}/companyCredits', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ImdbapiListTitleCompanyCreditsResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def i_mdb_api_service_list_title_credits(self, title_id, **kwargs):  # noqa: E501
        """List credits for a title  # noqa: E501

        Retrieve the credits associated with a specific title.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_list_title_credits(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: Required. IMDb title ID in the format \"tt1234567\". (required)
        :param list[str] categories: Optional. The categories of credits to filter by.
        :param int page_size: Optional. The maximum number of credits to return per page. If not specified, a default value will be used.  The value must be between 1 and 50. Default is 20.
        :param str page_token: Optional. Token for pagination, if applicable.
        :return: ImdbapiListTitleCreditsResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.i_mdb_api_service_list_title_credits_with_http_info(title_id, **kwargs)  # noqa: E501
        else:
            (data) = self.i_mdb_api_service_list_title_credits_with_http_info(title_id, **kwargs)  # noqa: E501
            return data

    def i_mdb_api_service_list_title_credits_with_http_info(self, title_id, **kwargs):  # noqa: E501
        """List credits for a title  # noqa: E501

        Retrieve the credits associated with a specific title.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_list_title_credits_with_http_info(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: Required. IMDb title ID in the format \"tt1234567\". (required)
        :param list[str] categories: Optional. The categories of credits to filter by.
        :param int page_size: Optional. The maximum number of credits to return per page. If not specified, a default value will be used.  The value must be between 1 and 50. Default is 20.
        :param str page_token: Optional. Token for pagination, if applicable.
        :return: ImdbapiListTitleCreditsResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['title_id', 'categories', 'page_size', 'page_token']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method i_mdb_api_service_list_title_credits" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'title_id' is set
        if self.api_client.client_side_validation and ('title_id' not in params or
                                                       params['title_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `title_id` when calling `i_mdb_api_service_list_title_credits`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'title_id' in params:
            path_params['titleId'] = params['title_id']  # noqa: E501

        query_params = []
        if 'categories' in params:
            query_params.append(('categories', params['categories']))  # noqa: E501
            collection_formats['categories'] = 'multi'  # noqa: E501
        if 'page_size' in params:
            query_params.append(('pageSize', params['page_size']))  # noqa: E501
        if 'page_token' in params:
            query_params.append(('pageToken', params['page_token']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/titles/{titleId}/credits', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ImdbapiListTitleCreditsResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def i_mdb_api_service_list_title_episodes(self, title_id, **kwargs):  # noqa: E501
        """List episodes for a title  # noqa: E501

        Retrieve the episodes associated with a specific title.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_list_title_episodes(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: Required. IMDb title ID in the format \"tt1234567\". (required)
        :param str season: Optional. The season number to filter episodes by.
        :param int page_size: Optional. The maximum number of episodes to return per page. If not specified, a default value will be used.  The value must be between 1 and 50. Default is 20.
        :param str page_token: Optional. Token for pagination, if applicable.
        :return: ImdbapiListTitleEpisodesResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.i_mdb_api_service_list_title_episodes_with_http_info(title_id, **kwargs)  # noqa: E501
        else:
            (data) = self.i_mdb_api_service_list_title_episodes_with_http_info(title_id, **kwargs)  # noqa: E501
            return data

    def i_mdb_api_service_list_title_episodes_with_http_info(self, title_id, **kwargs):  # noqa: E501
        """List episodes for a title  # noqa: E501

        Retrieve the episodes associated with a specific title.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_list_title_episodes_with_http_info(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: Required. IMDb title ID in the format \"tt1234567\". (required)
        :param str season: Optional. The season number to filter episodes by.
        :param int page_size: Optional. The maximum number of episodes to return per page. If not specified, a default value will be used.  The value must be between 1 and 50. Default is 20.
        :param str page_token: Optional. Token for pagination, if applicable.
        :return: ImdbapiListTitleEpisodesResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['title_id', 'season', 'page_size', 'page_token']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method i_mdb_api_service_list_title_episodes" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'title_id' is set
        if self.api_client.client_side_validation and ('title_id' not in params or
                                                       params['title_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `title_id` when calling `i_mdb_api_service_list_title_episodes`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'title_id' in params:
            path_params['titleId'] = params['title_id']  # noqa: E501

        query_params = []
        if 'season' in params:
            query_params.append(('season', params['season']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('pageSize', params['page_size']))  # noqa: E501
        if 'page_token' in params:
            query_params.append(('pageToken', params['page_token']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/titles/{titleId}/episodes', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ImdbapiListTitleEpisodesResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def i_mdb_api_service_list_title_images(self, title_id, **kwargs):  # noqa: E501
        """List images for a title  # noqa: E501

        Retrieve the images associated with a specific title.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_list_title_images(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: Required. IMDb title ID in the format \"tt1234567\". (required)
        :param list[str] types: Optional. The types of images to filter by. If not specified, all types are returned.
        :param int page_size: Optional. The maximum number of images to return per page. If not specified, a default value will be used.  The value must be between 1 and 50. Default is 20.
        :param str page_token: Optional. Token for pagination, if applicable.
        :return: ImdbapiListTitleImagesResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.i_mdb_api_service_list_title_images_with_http_info(title_id, **kwargs)  # noqa: E501
        else:
            (data) = self.i_mdb_api_service_list_title_images_with_http_info(title_id, **kwargs)  # noqa: E501
            return data

    def i_mdb_api_service_list_title_images_with_http_info(self, title_id, **kwargs):  # noqa: E501
        """List images for a title  # noqa: E501

        Retrieve the images associated with a specific title.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_list_title_images_with_http_info(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: Required. IMDb title ID in the format \"tt1234567\". (required)
        :param list[str] types: Optional. The types of images to filter by. If not specified, all types are returned.
        :param int page_size: Optional. The maximum number of images to return per page. If not specified, a default value will be used.  The value must be between 1 and 50. Default is 20.
        :param str page_token: Optional. Token for pagination, if applicable.
        :return: ImdbapiListTitleImagesResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['title_id', 'types', 'page_size', 'page_token']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method i_mdb_api_service_list_title_images" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'title_id' is set
        if self.api_client.client_side_validation and ('title_id' not in params or
                                                       params['title_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `title_id` when calling `i_mdb_api_service_list_title_images`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'title_id' in params:
            path_params['titleId'] = params['title_id']  # noqa: E501

        query_params = []
        if 'types' in params:
            query_params.append(('types', params['types']))  # noqa: E501
            collection_formats['types'] = 'multi'  # noqa: E501
        if 'page_size' in params:
            query_params.append(('pageSize', params['page_size']))  # noqa: E501
        if 'page_token' in params:
            query_params.append(('pageToken', params['page_token']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/titles/{titleId}/images', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ImdbapiListTitleImagesResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def i_mdb_api_service_list_title_parents_guide(self, title_id, **kwargs):  # noqa: E501
        """List parents guide for a title  # noqa: E501

        Retrieve the parents guide associated with a specific title.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_list_title_parents_guide(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: Required. IMDb title ID in the format \"tt1234567\". (required)
        :return: ImdbapiListTitleParentsGuideResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.i_mdb_api_service_list_title_parents_guide_with_http_info(title_id, **kwargs)  # noqa: E501
        else:
            (data) = self.i_mdb_api_service_list_title_parents_guide_with_http_info(title_id, **kwargs)  # noqa: E501
            return data

    def i_mdb_api_service_list_title_parents_guide_with_http_info(self, title_id, **kwargs):  # noqa: E501
        """List parents guide for a title  # noqa: E501

        Retrieve the parents guide associated with a specific title.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_list_title_parents_guide_with_http_info(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: Required. IMDb title ID in the format \"tt1234567\". (required)
        :return: ImdbapiListTitleParentsGuideResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['title_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method i_mdb_api_service_list_title_parents_guide" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'title_id' is set
        if self.api_client.client_side_validation and ('title_id' not in params or
                                                       params['title_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `title_id` when calling `i_mdb_api_service_list_title_parents_guide`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'title_id' in params:
            path_params['titleId'] = params['title_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/titles/{titleId}/parentsGuide', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ImdbapiListTitleParentsGuideResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def i_mdb_api_service_list_title_release_dates(self, title_id, **kwargs):  # noqa: E501
        """List release dates for a title  # noqa: E501

        Retrieve the release dates associated with a specific title.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_list_title_release_dates(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: Required. IMDb title ID in the format \"tt1234567\". (required)
        :param int page_size: Optional. The maximum number of credits to return per page. If not specified, a default value will be used.  The value must be between 1 and 50. Default is 20.
        :param str page_token: Optional. Token for pagination, if applicable.
        :return: ImdbapiListTitleReleaseDatesResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.i_mdb_api_service_list_title_release_dates_with_http_info(title_id, **kwargs)  # noqa: E501
        else:
            (data) = self.i_mdb_api_service_list_title_release_dates_with_http_info(title_id, **kwargs)  # noqa: E501
            return data

    def i_mdb_api_service_list_title_release_dates_with_http_info(self, title_id, **kwargs):  # noqa: E501
        """List release dates for a title  # noqa: E501

        Retrieve the release dates associated with a specific title.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_list_title_release_dates_with_http_info(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: Required. IMDb title ID in the format \"tt1234567\". (required)
        :param int page_size: Optional. The maximum number of credits to return per page. If not specified, a default value will be used.  The value must be between 1 and 50. Default is 20.
        :param str page_token: Optional. Token for pagination, if applicable.
        :return: ImdbapiListTitleReleaseDatesResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['title_id', 'page_size', 'page_token']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method i_mdb_api_service_list_title_release_dates" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'title_id' is set
        if self.api_client.client_side_validation and ('title_id' not in params or
                                                       params['title_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `title_id` when calling `i_mdb_api_service_list_title_release_dates`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'title_id' in params:
            path_params['titleId'] = params['title_id']  # noqa: E501

        query_params = []
        if 'page_size' in params:
            query_params.append(('pageSize', params['page_size']))  # noqa: E501
        if 'page_token' in params:
            query_params.append(('pageToken', params['page_token']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/titles/{titleId}/releaseDates', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ImdbapiListTitleReleaseDatesResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def i_mdb_api_service_list_title_seasons(self, title_id, **kwargs):  # noqa: E501
        """List seasons for a title  # noqa: E501

        Retrieve the seasons associated with a specific title.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_list_title_seasons(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: Required. IMDb title ID in the format \"tt1234567\". (required)
        :return: ImdbapiListTitleSeasonsResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.i_mdb_api_service_list_title_seasons_with_http_info(title_id, **kwargs)  # noqa: E501
        else:
            (data) = self.i_mdb_api_service_list_title_seasons_with_http_info(title_id, **kwargs)  # noqa: E501
            return data

    def i_mdb_api_service_list_title_seasons_with_http_info(self, title_id, **kwargs):  # noqa: E501
        """List seasons for a title  # noqa: E501

        Retrieve the seasons associated with a specific title.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_list_title_seasons_with_http_info(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: Required. IMDb title ID in the format \"tt1234567\". (required)
        :return: ImdbapiListTitleSeasonsResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['title_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method i_mdb_api_service_list_title_seasons" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'title_id' is set
        if self.api_client.client_side_validation and ('title_id' not in params or
                                                       params['title_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `title_id` when calling `i_mdb_api_service_list_title_seasons`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'title_id' in params:
            path_params['titleId'] = params['title_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/titles/{titleId}/seasons', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ImdbapiListTitleSeasonsResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def i_mdb_api_service_list_title_videos(self, title_id, **kwargs):  # noqa: E501
        """List videos for a title  # noqa: E501

        Retrieve the videos associated with a specific title.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_list_title_videos(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: Required. IMDb title ID in the format \"tt1234567\". (required)
        :param list[str] types: Optional. The types of videos to filter by. If not specified, all types are returned.
        :param int page_size: Optional. The maximum number of videos to return per page. If not specified, a default value will be used.  The value must be between 1 and 50. Default is 20.
        :param str page_token: Optional. Token for pagination, if applicable.
        :return: ImdbapiListTitleVideosResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.i_mdb_api_service_list_title_videos_with_http_info(title_id, **kwargs)  # noqa: E501
        else:
            (data) = self.i_mdb_api_service_list_title_videos_with_http_info(title_id, **kwargs)  # noqa: E501
            return data

    def i_mdb_api_service_list_title_videos_with_http_info(self, title_id, **kwargs):  # noqa: E501
        """List videos for a title  # noqa: E501

        Retrieve the videos associated with a specific title.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_list_title_videos_with_http_info(title_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str title_id: Required. IMDb title ID in the format \"tt1234567\". (required)
        :param list[str] types: Optional. The types of videos to filter by. If not specified, all types are returned.
        :param int page_size: Optional. The maximum number of videos to return per page. If not specified, a default value will be used.  The value must be between 1 and 50. Default is 20.
        :param str page_token: Optional. Token for pagination, if applicable.
        :return: ImdbapiListTitleVideosResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['title_id', 'types', 'page_size', 'page_token']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method i_mdb_api_service_list_title_videos" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'title_id' is set
        if self.api_client.client_side_validation and ('title_id' not in params or
                                                       params['title_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `title_id` when calling `i_mdb_api_service_list_title_videos`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'title_id' in params:
            path_params['titleId'] = params['title_id']  # noqa: E501

        query_params = []
        if 'types' in params:
            query_params.append(('types', params['types']))  # noqa: E501
            collection_formats['types'] = 'multi'  # noqa: E501
        if 'page_size' in params:
            query_params.append(('pageSize', params['page_size']))  # noqa: E501
        if 'page_token' in params:
            query_params.append(('pageToken', params['page_token']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/titles/{titleId}/videos', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ImdbapiListTitleVideosResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def i_mdb_api_service_list_titles(self, **kwargs):  # noqa: E501
        """List titles  # noqa: E501

        Retrieve a list of titles with optional filters.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_list_titles(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] types: Optional. The type of titles to filter by. If not specified, all types are returned.   - MOVIE: Represents a movie title.  - TV_SERIES: Represents a TV series title.  - TV_MINI_SERIES: Represents a TV mini-series title.  - TV_SPECIAL: Represents a TV special title.  - TV_MOVIE: Represents a TV movie title.  - SHORT: Represents a short title.  - VIDEO: Represents a video title.  - VIDEO_GAME: Represents a video game title.
        :param list[str] genres: Optional. The genres to filter titles by. If not specified, titles from all genres are returned.
        :param list[str] country_codes: Optional. The ISO 3166-1 alpha-2 country codes to filter titles by. If not specified, titles from all countries are returned. Example: \"US\" for United States, \"GB\" for United Kingdom.
        :param list[str] language_codes: Optional. The ISO 639-1 or ISO 639-2 language codes to filter titles by. If not specified, titles in all languages are returned.
        :param list[str] name_ids: Optional. The IDs of names to filter titles by.
        :param list[str] interest_ids: Optional. The IDs of interests to filter titles by. If not specified, titles associated with all interests are returned.
        :param int start_year: Optional. The start year for filtering titles.
        :param int end_year: Optional. The end year for filtering titles.
        :param int min_vote_count: Optional. The minimum number of votes a title must have to be included. If not specified, titles with any number of votes are included. The value must be between 0 and 1,000,000,000. Default is 0.
        :param int max_vote_count: Optional. The maximum number of votes a title can have to be included. If not specified, titles with any number of votes are included. The value must be between 0 and 1,000,000,000.
        :param float min_aggregate_rating: Optional. The minimum rating a title must have to be included. If not specified, titles with any rating are included. The value must be between 0.0 and 10.0.
        :param float max_aggregate_rating: Optional. The maximum rating a title can have to be included. If not specified, titles with any rating are included. The value must be between 0.0 and 10.0.
        :param str sort_by: Optional. The sorting order for the titles. If not specified, titles are sorted by popularity.   - SORT_BY_POPULARITY: Sort by popularity. This is used to rank titles based on their popularity, which can be influenced by various factors such as viewership, ratings, and cultural impact.  - SORT_BY_RELEASE_DATE: Sort by release date. This is used to rank titles based on their release dates, with newer titles typically appearing before older ones.  - SORT_BY_USER_RATING: Sort by user rating. This is used to rank titles based on the average user rating, which reflects the overall audience reception.  - SORT_BY_USER_RATING_COUNT: Sort by user rating count. This is used to rank titles based on the number of user ratings they have received, which can indicate the level of engagement or popularity among viewers.  - SORT_BY_YEAR: Sort by year. This is used to rank titles based on their release year, with newer titles typically appearing before older ones.
        :param str sort_order: Optional. The sorting order for the titles. If not specified, titles are sorted in ascending order.   - ASC: Sort in ascending order.  - DESC: Sort in descending order.
        :param str page_token: Optional. Token for pagination, if applicable.
        :return: ImdbapiListTitlesResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.i_mdb_api_service_list_titles_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.i_mdb_api_service_list_titles_with_http_info(**kwargs)  # noqa: E501
            return data

    def i_mdb_api_service_list_titles_with_http_info(self, **kwargs):  # noqa: E501
        """List titles  # noqa: E501

        Retrieve a list of titles with optional filters.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_list_titles_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] types: Optional. The type of titles to filter by. If not specified, all types are returned.   - MOVIE: Represents a movie title.  - TV_SERIES: Represents a TV series title.  - TV_MINI_SERIES: Represents a TV mini-series title.  - TV_SPECIAL: Represents a TV special title.  - TV_MOVIE: Represents a TV movie title.  - SHORT: Represents a short title.  - VIDEO: Represents a video title.  - VIDEO_GAME: Represents a video game title.
        :param list[str] genres: Optional. The genres to filter titles by. If not specified, titles from all genres are returned.
        :param list[str] country_codes: Optional. The ISO 3166-1 alpha-2 country codes to filter titles by. If not specified, titles from all countries are returned. Example: \"US\" for United States, \"GB\" for United Kingdom.
        :param list[str] language_codes: Optional. The ISO 639-1 or ISO 639-2 language codes to filter titles by. If not specified, titles in all languages are returned.
        :param list[str] name_ids: Optional. The IDs of names to filter titles by.
        :param list[str] interest_ids: Optional. The IDs of interests to filter titles by. If not specified, titles associated with all interests are returned.
        :param int start_year: Optional. The start year for filtering titles.
        :param int end_year: Optional. The end year for filtering titles.
        :param int min_vote_count: Optional. The minimum number of votes a title must have to be included. If not specified, titles with any number of votes are included. The value must be between 0 and 1,000,000,000. Default is 0.
        :param int max_vote_count: Optional. The maximum number of votes a title can have to be included. If not specified, titles with any number of votes are included. The value must be between 0 and 1,000,000,000.
        :param float min_aggregate_rating: Optional. The minimum rating a title must have to be included. If not specified, titles with any rating are included. The value must be between 0.0 and 10.0.
        :param float max_aggregate_rating: Optional. The maximum rating a title can have to be included. If not specified, titles with any rating are included. The value must be between 0.0 and 10.0.
        :param str sort_by: Optional. The sorting order for the titles. If not specified, titles are sorted by popularity.   - SORT_BY_POPULARITY: Sort by popularity. This is used to rank titles based on their popularity, which can be influenced by various factors such as viewership, ratings, and cultural impact.  - SORT_BY_RELEASE_DATE: Sort by release date. This is used to rank titles based on their release dates, with newer titles typically appearing before older ones.  - SORT_BY_USER_RATING: Sort by user rating. This is used to rank titles based on the average user rating, which reflects the overall audience reception.  - SORT_BY_USER_RATING_COUNT: Sort by user rating count. This is used to rank titles based on the number of user ratings they have received, which can indicate the level of engagement or popularity among viewers.  - SORT_BY_YEAR: Sort by year. This is used to rank titles based on their release year, with newer titles typically appearing before older ones.
        :param str sort_order: Optional. The sorting order for the titles. If not specified, titles are sorted in ascending order.   - ASC: Sort in ascending order.  - DESC: Sort in descending order.
        :param str page_token: Optional. Token for pagination, if applicable.
        :return: ImdbapiListTitlesResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['types', 'genres', 'country_codes', 'language_codes', 'name_ids', 'interest_ids', 'start_year', 'end_year', 'min_vote_count', 'max_vote_count', 'min_aggregate_rating', 'max_aggregate_rating', 'sort_by', 'sort_order', 'page_token']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method i_mdb_api_service_list_titles" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'types' in params:
            query_params.append(('types', params['types']))  # noqa: E501
            collection_formats['types'] = 'multi'  # noqa: E501
        if 'genres' in params:
            query_params.append(('genres', params['genres']))  # noqa: E501
            collection_formats['genres'] = 'multi'  # noqa: E501
        if 'country_codes' in params:
            query_params.append(('countryCodes', params['country_codes']))  # noqa: E501
            collection_formats['countryCodes'] = 'multi'  # noqa: E501
        if 'language_codes' in params:
            query_params.append(('languageCodes', params['language_codes']))  # noqa: E501
            collection_formats['languageCodes'] = 'multi'  # noqa: E501
        if 'name_ids' in params:
            query_params.append(('nameIds', params['name_ids']))  # noqa: E501
            collection_formats['nameIds'] = 'multi'  # noqa: E501
        if 'interest_ids' in params:
            query_params.append(('interestIds', params['interest_ids']))  # noqa: E501
            collection_formats['interestIds'] = 'multi'  # noqa: E501
        if 'start_year' in params:
            query_params.append(('startYear', params['start_year']))  # noqa: E501
        if 'end_year' in params:
            query_params.append(('endYear', params['end_year']))  # noqa: E501
        if 'min_vote_count' in params:
            query_params.append(('minVoteCount', params['min_vote_count']))  # noqa: E501
        if 'max_vote_count' in params:
            query_params.append(('maxVoteCount', params['max_vote_count']))  # noqa: E501
        if 'min_aggregate_rating' in params:
            query_params.append(('minAggregateRating', params['min_aggregate_rating']))  # noqa: E501
        if 'max_aggregate_rating' in params:
            query_params.append(('maxAggregateRating', params['max_aggregate_rating']))  # noqa: E501
        if 'sort_by' in params:
            query_params.append(('sortBy', params['sort_by']))  # noqa: E501
        if 'sort_order' in params:
            query_params.append(('sortOrder', params['sort_order']))  # noqa: E501
        if 'page_token' in params:
            query_params.append(('pageToken', params['page_token']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/titles', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ImdbapiListTitlesResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def i_mdb_api_service_search_titles(self, query, **kwargs):  # noqa: E501
        """Search titles by query  # noqa: E501

        Search for titles using a query string.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_search_titles(query, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str query: Required. The search query for titles. (required)
        :param int limit: Optional. Limit the number of results returned. Maximum is 50.
        :return: ImdbapiSearchTitlesResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.i_mdb_api_service_search_titles_with_http_info(query, **kwargs)  # noqa: E501
        else:
            (data) = self.i_mdb_api_service_search_titles_with_http_info(query, **kwargs)  # noqa: E501
            return data

    def i_mdb_api_service_search_titles_with_http_info(self, query, **kwargs):  # noqa: E501
        """Search titles by query  # noqa: E501

        Search for titles using a query string.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.i_mdb_api_service_search_titles_with_http_info(query, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str query: Required. The search query for titles. (required)
        :param int limit: Optional. Limit the number of results returned. Maximum is 50.
        :return: ImdbapiSearchTitlesResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['query', 'limit']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method i_mdb_api_service_search_titles" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'query' is set
        if self.api_client.client_side_validation and ('query' not in params or
                                                       params['query'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `query` when calling `i_mdb_api_service_search_titles`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'query' in params:
            query_params.append(('query', params['query']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/search/titles', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ImdbapiSearchTitlesResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
